//! <auto-generated> by tools/ContractsGen from ClubShell.Contracts v1.0.0 — edit only inside MANUAL blocks

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;

use crate::error::IpcError;

wire_enum! {
    /// Why an account-pool lease is released.
    AccountLeaseReleaseReason {
        /// Game exited.
        Exit = "exit",
        /// Session ended.
        SessionEnd = "sessionEnd",
        /// Launch failed.
        LaunchFailed = "launchFailed",
        /// Manual / admin release.
        Manual = "manual",
    }
}

wire_enum! {
    /// Action the Agent took in response to an anti-cheat finding.
    AntiCheatAction {
        /// Reported only.
        None = "none",
        /// Launch was refused (`antiCheatBlocked`).
        BlockedLaunch = "blockedLaunch",
        /// Running game was killed.
        KilledGame = "killedGame",
        /// Session was locked pending admin.
        LockedSession = "lockedSession",
    }
}

/// Well-known values of `AntiCheatReport.Check` (SERVER_API.md §4.14).
pub mod anti_cheat_checks {
    /// Required anti-cheat driver is not installed.
    pub const DRIVER_MISSING: &str = "driverMissing";
    /// Anti-cheat service is stopped.
    pub const SERVICE_STOPPED: &str = "serviceStopped";
    /// UEFI Secure Boot is off.
    pub const SECURE_BOOT_OFF: &str = "secureBootOff";
    /// TPM is absent or disabled.
    pub const TPM_OFF: &str = "tpmOff";
    /// Hypervisor-enforced code integrity is off.
    pub const HVCI_OFF: &str = "hvciOff";
    /// Windows test-signing mode is on.
    pub const TEST_SIGNING_ON: &str = "testSigningOn";
    /// A blocked process was found running.
    pub const BLOCKED_PROCESS: &str = "blockedProcess";
    /// A foreign module was injected into a game process.
    pub const INJECTED_MODULE: &str = "injectedModule";
    /// Virtual machine detected.
    pub const VM_DETECTED: &str = "vmDetected";
    /// Debugger attached to a game process.
    pub const DEBUGGER_ATTACHED: &str = "debuggerAttached";
}

wire_enum! {
    /// Anti-cheat subsystem a game depends on.
    AntiCheatKind {
        /// No anti-cheat.
        None = "none",
        /// Easy Anti-Cheat.
        Eac = "eac",
        /// BattlEye.
        BattlEye = "battlEye",
        /// Riot Vanguard (kernel driver, Secure Boot / TPM prerequisites).
        Vanguard = "vanguard",
        /// FACEIT client.
        Faceit = "faceit",
        /// Activision Ricochet.
        Ricochet = "ricochet",
    }
}

/// Result of the pre-launch anti-cheat check, embedded in a `LaunchReport`.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct AntiCheatCheckResult {
    /// Subsystem checked.
    pub kind: AntiCheatKind,
    /// Whether prerequisites were satisfied.
    pub ok: bool,
    /// Failed check (`AntiCheatChecks`) when `ok` is `false`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

wire_enum! {
    /// Severity of an anti-cheat finding.
    AntiCheatSeverity {
        /// Informational.
        Info = "info",
        /// Soft violation; launch allowed unless policy blocks.
        Warning = "warning",
        /// Hard violation.
        Critical = "critical",
    }
}

/// Body of `POST /anticheat/report` and payload of the `anticheatViolation` agent event
/// (SERVER_API.md §4.14).
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AntiCheatReport {
    /// Reporting PC.
    pub pc_id: Uuid,
    /// Session during which the finding occurred, when any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_id: Option<Uuid>,
    /// Logged-in user, when any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Uuid>,
    /// Game concerned, when any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub game_id: Option<Uuid>,
    /// Subsystem.
    pub kind: AntiCheatKind,
    /// Check identifier (`AntiCheatChecks`).
    pub check: String,
    /// Severity.
    pub severity: AntiCheatSeverity,
    /// Structured evidence (process names, module paths, registry values). Never contains
    /// credentials.
    pub details: Value,
    /// Time of the finding.
    #[serde(with = "crate::wire::ts")]
    pub at: DateTime<Utc>,
    /// Action the Agent took.
    pub action_taken: AntiCheatAction,
}

/// Non-game application allowed on the kiosk (IPC_PROTOCOL.md §6.10).
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct App {
    /// App id.
    pub id: Uuid,
    /// Title.
    pub title: String,
    /// Executable path (allow-listed by the Agent).
    pub exe_path: String,
    /// Icon URL.
    pub icon_url: String,
    /// Category (`AppCategories`).
    pub category: String,
    /// Allowed after policy evaluation.
    pub allowed: bool,
}

/// Well-known values of `App.Category`.
pub mod app_categories {
    /// Web browser.
    pub const BROWSER: &str = "browser";
    /// Voice chat client.
    pub const VOICE: &str = "voice";
    /// Media player.
    pub const MEDIA: &str = "media";
    /// Utility.
    pub const TOOL: &str = "tool";
}

/// Pre-signed download of a user's cloud-save bundle.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct CloudSaveDownload {
    /// Pre-signed HTTPS URL.
    pub url: String,
    /// Lower-case hex SHA-256 of the bundle.
    pub sha256: String,
    /// Bundle size.
    pub size_bytes: i64,
}

/// Cloud-save bundle the Agent uploaded before releasing a lease.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct CloudSaveUpload {
    /// Pre-signed URL the bundle was `PUT` to (from `SaveUploadTarget`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub upload_url: Option<String>,
    /// Lower-case hex SHA-256 of the bundle.
    pub sha256: String,
    /// Bundle size.
    pub size_bytes: i64,
}

/// Body of `POST /games/{id}/accounts/{leaseId}/release`.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct AccountLeaseRelease {
    /// Release reason.
    pub reason: AccountLeaseReleaseReason,
    /// Uploaded save bundle, when cloud save is enabled.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cloud_save: Option<CloudSaveUpload>,
}

/// Response of `games.installStatus`.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GameInstallStatus {
    /// Game id.
    pub game_id: Uuid,
    /// Install present and verified.
    pub installed: bool,
    /// Resolved install directory.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub install_path: Option<String>,
    /// Size on disk in GB.
    #[serde(with = "crate::wire::num")]
    pub size_gb: f64,
    /// Detected version.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Last successful verification.
    #[serde(
        default,
        with = "crate::wire::ts_opt",
        skip_serializing_if = "Option::is_none"
    )]
    pub verified_at: Option<DateTime<Utc>>,
    /// Launcher client present and logged in (where detectable).
    pub launcher_ready: bool,
}

/// Minimum hardware specification of a game.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct GameMinSpec {
    /// CPU description.
    pub cpu: String,
    /// GPU description.
    pub gpu: String,
    /// RAM in MiB.
    pub ram_mb: i32,
}

wire_enum! {
    /// Lifecycle state of a launched game process.
    GameState {
        /// Launcher invoked; waiting for the game window/process.
        Launching = "launching",
        /// Game process running.
        Running = "running",
        /// Exited normally.
        Exited = "exited",
        /// Launch failed.
        Failed = "failed",
        /// Killed by the Agent (session end, admin, policy).
        Killed = "killed",
    }
}

wire_enum! {
    /// Sort order for `games.list`.
    GamesSort {
        /// By server popularity rank, descending.
        Popularity = "popularity",
        /// By title, ascending.
        Title = "title",
        /// By last played (current user), most recent first.
        LastPlayed = "lastPlayed",
    }
}

wire_enum! {
    /// Which lifecycle point a `LaunchReport` describes.
    LaunchReportPhase {
        /// Reported right after launch (success or failure).
        Launch = "launch",
        /// Reported when the game exits.
        Exit = "exit",
    }
}

/// Outcome of a launch (IPC_PROTOCOL.md §6.9). Over IPC failures are returned as errors, so `ok` is
/// always `true` there.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct LaunchResult {
    /// Success flag.
    pub ok: bool,
    /// Game process id when started.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pid: Option<i32>,
    /// Launch time.
    #[serde(with = "crate::wire::ts")]
    pub started_at: DateTime<Utc>,
    /// Account-pool lease used, when any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_lease_id: Option<Uuid>,
    /// Failure details when `ok` is `false`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<IpcError>,
}

wire_enum! {
    /// Game launcher / store client used to start a game.
    LauncherType {
        /// Steam (`steam://rungameid/<appid>`).
        Steam = "steam",
        /// Epic Games Launcher.
        Epic = "epic",
        /// Battle.net.
        BattleNet = "battleNet",
        /// Riot Client.
        Riot = "riot",
        /// EA app.
        Ea = "ea",
        /// Ubisoft Connect.
        Ubisoft = "ubisoft",
        /// Plain executable, no launcher.
        Exe = "exe",
    }
}

/// Account-pool lease (`GET /games/{id}/accounts/lease`, SERVER_API.md §4.6). `secret` is
/// AES-256-GCM encrypted with a per-agent key derived from the signing secret (HKDF-SHA256, info
/// `account-pool`), base64 `nonce||ciphertext||tag`. Never logged.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AccountLease {
    /// Lease id.
    pub lease_id: Uuid,
    /// Launcher the credentials belong to.
    pub launcher: LauncherType,
    /// Account login.
    pub username: String,
    /// Encrypted password or token.
    pub secret: String,
    /// Launcher-specific extras (`steamGuardSecret`, `authenticatorSeed`, `region`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extra: Option<Value>,
    /// Lease TTL.
    #[serde(with = "crate::wire::ts")]
    pub expires_at: DateTime<Utc>,
    /// Save bundle to restore before launch, when any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cloud_save: Option<CloudSaveDownload>,
}

/// Catalogue game (IPC_PROTOCOL.md §6.8). Local-only fields (`installed`, `installPath`) are filled
/// by the Agent's scan.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Game {
    /// Game id.
    pub id: Uuid,
    /// Localized title.
    pub title: String,
    /// Launcher used to start it.
    pub launcher: LauncherType,
    /// Steam appid, Epic namespace:item, Battle.net code, etc.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub launcher_app_id: Option<String>,
    /// Executable; required for `LauncherType.Exe`; may be relative to `installPath`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exe_path: Option<String>,
    /// Extra command line.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub args: Option<String>,
    /// Resolved local install directory.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub install_path: Option<String>,
    /// Local scan result.
    pub installed: bool,
    /// Categories.
    pub category: Vec<String>,
    /// Tags.
    pub tags: Vec<String>,
    /// Cover image (2:3).
    pub cover_url: String,
    /// Wide hero image.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hero_url: Option<String>,
    /// Trailer / background video.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video_url: Option<String>,
    /// Localized description; may be empty.
    pub description: String,
    /// Minimum age; 0 = none.
    pub age_rating: i32,
    /// Server rank score.
    pub popularity: i32,
    /// Last launch by the current user.
    #[serde(
        default,
        with = "crate::wire::ts_opt",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_played_at: Option<DateTime<Utc>>,
    /// Needs an account-pool lease.
    pub requires_account: bool,
    /// Anti-cheat subsystem.
    pub anti_cheat: AntiCheatKind,
    /// Minimum spec.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub min_spec: Option<GameMinSpec>,
    /// Install size in GB (1 fraction digit).
    #[serde(with = "crate::wire::num")]
    pub size_gb: f64,
    /// Installed/catalogue version.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

/// Body of `POST /games/{id}/launch-report` (SERVER_API.md §4.6).
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct LaunchReport {
    /// Session.
    pub session_id: Uuid,
    /// Player.
    pub user_id: Uuid,
    /// Launch outcome.
    pub result: LaunchResult,
    /// Launch latency in milliseconds.
    pub duration_ms: i32,
    /// Launcher used.
    pub launcher: LauncherType,
    /// Pre-launch anti-cheat check.
    pub anti_cheat: AntiCheatCheckResult,
    /// Lifecycle point.
    pub phase: LaunchReportPhase,
    /// Process exit code (`LaunchReportPhase.Exit`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i32>,
    /// Seconds played (`LaunchReportPhase.Exit`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub played_sec: Option<i32>,
}

/// Screen resolution requested for a launch.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[serde(rename_all = "camelCase")]
pub struct Resolution {
    /// Width in pixels.
    pub width: i32,
    /// Height in pixels.
    pub height: i32,
}

/// Full launch request as executed by the Agent (IPC_PROTOCOL.md §6.9); also the payload of the
/// `launchGame` server command.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct LaunchRequest {
    /// Game to launch.
    pub game_id: Uuid,
    /// Active session.
    pub session_id: Uuid,
    /// Player.
    pub user_id: Uuid,
    /// Lease a pooled account and inject credentials.
    pub use_account_pool: bool,
    /// Reuse an existing lease.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_lease_id: Option<Uuid>,
    /// Extra command line (policy-sanitized).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extra_args: Option<String>,
    /// Requested resolution.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolution: Option<Resolution>,
    /// Seconds to wait for the game process/window before failing.
    pub launch_timeout_sec: i32,
}

/// Game process tracked by the Agent (IPC_PROTOCOL.md §6.9).
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RunningGame {
    /// Game id.
    pub game_id: Uuid,
    /// Game title.
    pub title: String,
    /// Process id.
    pub pid: i32,
    /// Launch time.
    #[serde(with = "crate::wire::ts")]
    pub started_at: DateTime<Utc>,
    /// Account-pool lease in use, when any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub account_lease_id: Option<Uuid>,
    /// Current state.
    pub state: GameState,
}

/// Response of `GET /games/{id}/accounts/{leaseId}/save-upload`.
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct SaveUploadTarget {
    /// Pre-signed `PUT` URL.
    pub upload_url: String,
    /// URL expiry.
    #[serde(with = "crate::wire::ts")]
    pub expires_at: DateTime<Utc>,
    /// Maximum accepted bundle size.
    pub max_bytes: i64,
}

// ---- BEGIN MANUAL ----
impl GameState {
    /// `true` for terminal states (`exited`, `failed`, `killed`).
    pub const fn is_terminal(self) -> bool {
        matches!(
            self,
            GameState::Exited | GameState::Failed | GameState::Killed
        )
    }
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
impl LaunchResult {
    /// Successful result.
    pub fn success(pid: i32, started_at: DateTime<Utc>, account_lease_id: Option<Uuid>) -> Self {
        Self {
            ok: true,
            pid: Some(pid),
            started_at,
            account_lease_id,
            error: None,
        }
    }

    /// Failed result.
    pub fn failure(
        error: IpcError,
        started_at: DateTime<Utc>,
        account_lease_id: Option<Uuid>,
    ) -> Self {
        Self {
            ok: false,
            pid: None,
            started_at,
            account_lease_id,
            error: Some(error),
        }
    }
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::assert_wire;
    use chrono::TimeZone;

    #[test]
    fn enum_wire_values() {
        assert_wire(
            LauncherType::ALL,
            &["steam", "epic", "battleNet", "riot", "ea", "ubisoft", "exe"],
        );
        assert_wire(
            AntiCheatKind::ALL,
            &["none", "eac", "battlEye", "vanguard", "faceit", "ricochet"],
        );
        assert_wire(AntiCheatSeverity::ALL, &["info", "warning", "critical"]);
        assert_wire(
            AntiCheatAction::ALL,
            &["none", "blockedLaunch", "killedGame", "lockedSession"],
        );
        assert_wire(GamesSort::ALL, &["popularity", "title", "lastPlayed"]);
        assert_wire(
            GameState::ALL,
            &["launching", "running", "exited", "failed", "killed"],
        );
        assert_wire(
            AccountLeaseReleaseReason::ALL,
            &["exit", "sessionEnd", "launchFailed", "manual"],
        );
        assert_wire(LaunchReportPhase::ALL, &["launch", "exit"]);
        assert!(GameState::Killed.is_terminal());
        assert!(!GameState::Launching.is_terminal());
    }

    #[test]
    fn game_json() {
        let g = Game {
            id: Uuid::nil(),
            title: "CS2".into(),
            launcher: LauncherType::Steam,
            launcher_app_id: Some("730".into()),
            exe_path: None,
            args: None,
            install_path: Some(r"D:\Games\cs2".into()),
            installed: true,
            category: vec!["fps".into()],
            tags: vec![],
            cover_url: "https://c".into(),
            hero_url: None,
            video_url: None,
            description: String::new(),
            age_rating: 16,
            popularity: 100,
            last_played_at: None,
            requires_account: true,
            anti_cheat: AntiCheatKind::None,
            min_spec: Some(GameMinSpec {
                cpu: "i5".into(),
                gpu: "GTX 1060".into(),
                ram_mb: 8192,
            }),
            size_gb: 35.5,
            version: None,
        };
        let json = serde_json::to_string(&g).unwrap();
        assert_eq!(
            json,
            r#"{"id":"00000000-0000-0000-0000-000000000000","title":"CS2","launcher":"steam","launcherAppId":"730","installPath":"D:\\Games\\cs2","installed":true,"category":["fps"],"tags":[],"coverUrl":"https://c","description":"","ageRating":16,"popularity":100,"requiresAccount":true,"antiCheat":"none","minSpec":{"cpu":"i5","gpu":"GTX 1060","ramMb":8192},"sizeGb":35.5}"#
        );
        assert_eq!(serde_json::from_str::<Game>(&json).unwrap(), g);
        // Explicit nulls from the server are accepted.
        let with_nulls = json.replace(
            r#""launcherAppId":"730","#,
            r#""launcherAppId":null,"exePath":null,"lastPlayedAt":null,"#,
        );
        let back: Game = serde_json::from_str(&with_nulls).unwrap();
        assert_eq!(back.launcher_app_id, None);
    }

    #[test]
    fn launch_types_json() {
        let at = Utc.with_ymd_and_hms(2026, 9, 21, 10, 21, 0).unwrap();
        let ok = LaunchResult::success(7788, at, None);
        assert_eq!(
            serde_json::to_string(&ok).unwrap(),
            r#"{"ok":true,"pid":7788,"startedAt":"2026-09-21T10:21:00.000Z"}"#
        );
        let failed = LaunchResult::failure(IpcError::account_pool_exhausted(), at, None);
        assert_eq!(
            serde_json::to_string(&failed).unwrap(),
            r#"{"ok":false,"startedAt":"2026-09-21T10:21:00.000Z","error":{"code":"accountPoolExhausted","message":"No free pooled account","details":null}}"#
        );
        assert_eq!(
            serde_json::from_str::<LaunchResult>(&serde_json::to_string(&failed).unwrap()).unwrap(),
            failed
        );

        let req = LaunchRequest {
            game_id: Uuid::nil(),
            session_id: Uuid::nil(),
            user_id: Uuid::nil(),
            use_account_pool: true,
            account_lease_id: None,
            extra_args: None,
            resolution: Some(Resolution {
                width: 1920,
                height: 1080,
            }),
            launch_timeout_sec: 90,
        };
        assert_eq!(
            serde_json::to_string(&req).unwrap(),
            r#"{"gameId":"00000000-0000-0000-0000-000000000000","sessionId":"00000000-0000-0000-0000-000000000000","userId":"00000000-0000-0000-0000-000000000000","useAccountPool":true,"resolution":{"width":1920,"height":1080},"launchTimeoutSec":90}"#
        );
        let running = RunningGame {
            game_id: Uuid::nil(),
            title: "CS2".into(),
            pid: 1,
            started_at: at,
            account_lease_id: None,
            state: GameState::Running,
        };
        assert_eq!(
            serde_json::to_string(&running).unwrap(),
            r#"{"gameId":"00000000-0000-0000-0000-000000000000","title":"CS2","pid":1,"startedAt":"2026-09-21T10:21:00.000Z","state":"running"}"#
        );
        let report = LaunchReport {
            session_id: Uuid::nil(),
            user_id: Uuid::nil(),
            result: ok,
            duration_ms: 1500,
            launcher: LauncherType::Steam,
            anti_cheat: AntiCheatCheckResult {
                kind: AntiCheatKind::Vanguard,
                ok: false,
                reason: Some(anti_cheat_checks::SECURE_BOOT_OFF.into()),
            },
            phase: LaunchReportPhase::Exit,
            exit_code: Some(0),
            played_sec: Some(3600),
        };
        let json = serde_json::to_string(&report).unwrap();
        assert!(json.ends_with(r#""durationMs":1500,"launcher":"steam","antiCheat":{"kind":"vanguard","ok":false,"reason":"secureBootOff"},"phase":"exit","exitCode":0,"playedSec":3600}"#));
        assert_eq!(serde_json::from_str::<LaunchReport>(&json).unwrap(), report);
    }

    #[test]
    fn lease_and_report_json() {
        let at = Utc.with_ymd_and_hms(2026, 9, 21, 14, 0, 0).unwrap();
        let lease = AccountLease {
            lease_id: Uuid::nil(),
            launcher: LauncherType::Steam,
            username: "pool01".into(),
            secret: "enc".into(),
            extra: Some(serde_json::json!({ "region": "eu" })),
            expires_at: at,
            cloud_save: None,
        };
        let json = serde_json::to_string(&lease).unwrap();
        assert_eq!(
            json,
            r#"{"leaseId":"00000000-0000-0000-0000-000000000000","launcher":"steam","username":"pool01","secret":"enc","extra":{"region":"eu"},"expiresAt":"2026-09-21T14:00:00.000Z"}"#
        );
        assert_eq!(serde_json::from_str::<AccountLease>(&json).unwrap(), lease);
        let release = AccountLeaseRelease {
            reason: AccountLeaseReleaseReason::SessionEnd,
            cloud_save: Some(CloudSaveUpload {
                upload_url: None,
                sha256: "ab".into(),
                size_bytes: 10,
            }),
        };
        assert_eq!(
            serde_json::to_string(&release).unwrap(),
            r#"{"reason":"sessionEnd","cloudSave":{"sha256":"ab","sizeBytes":10}}"#
        );
        let report = AntiCheatReport {
            pc_id: Uuid::nil(),
            session_id: None,
            user_id: None,
            game_id: None,
            kind: AntiCheatKind::Eac,
            check: anti_cheat_checks::DRIVER_MISSING.into(),
            severity: AntiCheatSeverity::Critical,
            details: serde_json::json!({}),
            at,
            action_taken: AntiCheatAction::BlockedLaunch,
        };
        assert_eq!(
            serde_json::to_string(&report).unwrap(),
            r#"{"pcId":"00000000-0000-0000-0000-000000000000","kind":"eac","check":"driverMissing","severity":"critical","details":{},"at":"2026-09-21T14:00:00.000Z","actionTaken":"blockedLaunch"}"#
        );
    }
}
// ---- END MANUAL ----
