//! Mirror of `ClubShell.Contracts.Ipc.IpcEnvelope` (IPC_PROTOCOL.md §2) plus the pipe framing of
//! §1: `[u32 length LE][UTF-8 JSON]`, length excluding the prefix, at most [`MAX_FRAME_BYTES`].
//!
//! Entirely hand-written (`IpcKind` / `IpcEnvelope` are on ContractsGen's manual-type list, so the generator never
//! emits this module); the MANUAL block keeps it safe should that change.

// ---- BEGIN MANUAL ----
use chrono::{DateTime, Utc};
use serde::de::DeserializeOwned;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;

use crate::commands::{names, object_as};
use crate::error::{IpcError, ProtocolError};
use crate::{MAX_FRAME_BYTES, PROTOCOL_VERSION};

wire_enum! {
    /// Envelope kind (IPC_PROTOCOL.md §2).
    IpcKind {
        /// Shell → Agent request; exactly one `response` with the same id follows.
        Request = "request",
        /// Agent → Shell reply; copies the request id.
        Response = "response",
        /// Agent → Shell notification; fresh id, never answered.
        Event = "event",
    }
}

/// One pipe frame (IPC_PROTOCOL.md §2), serialized as `{ v, id, kind, name, ts, payload, error }`;
/// `payload` and `error` keys are always present (`null` when empty).
#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct IpcEnvelope {
    /// Protocol major; receivers reject unsupported values with `versionMismatch`.
    pub v: i32,
    /// Request id generated by the sender; a response copies it; events use a fresh id.
    pub id: Uuid,
    pub kind: IpcKind,
    /// `<domain>.<action>`; a response repeats the request name (except `sys.ping` → `sys.pong`).
    pub name: String,
    /// Sender wall clock (UTC). Informational only, never used for ordering.
    #[serde(with = "crate::wire::ts")]
    pub ts: DateTime<Utc>,
    /// Body; `None` when the message carries no data. Never an array or scalar at top level.
    pub payload: Option<Value>,
    /// Non-null only on a response; when set, `payload` is `None`.
    pub error: Option<IpcError>,
}

impl IpcEnvelope {
    /// Protocol major implemented by this crate.
    pub const CURRENT_VERSION: i32 = PROTOCOL_VERSION;

    /// Maximum JSON frame size in bytes (excluding the 4-byte length prefix).
    pub const MAX_FRAME_BYTES: usize = MAX_FRAME_BYTES;

    /// Supported protocol majors, for `VersionMismatchDetails`.
    pub const SUPPORTED_VERSIONS: &'static [i32] = &[Self::CURRENT_VERSION];

    /// `true` when protocol major `v` is accepted by this implementation.
    pub const fn is_version_supported(v: i32) -> bool {
        v == Self::CURRENT_VERSION
    }

    fn create(
        id: Uuid,
        kind: IpcKind,
        name: &str,
        payload: Option<Value>,
        error: Option<IpcError>,
    ) -> Self {
        Self {
            v: Self::CURRENT_VERSION,
            id,
            kind,
            name: name.to_owned(),
            ts: Utc::now(),
            payload,
            error,
        }
    }

    /// Request with a fresh id.
    pub fn request(name: &str, payload: Option<Value>) -> Self {
        Self::create(Uuid::new_v4(), IpcKind::Request, name, payload, None)
    }

    /// Request with a typed payload.
    pub fn request_with<T: Serialize>(name: &str, payload: &T) -> Result<Self, ProtocolError> {
        Ok(Self::request(name, Some(serde_json::to_value(payload)?)))
    }

    /// Successful response to `request_id`.
    pub fn response(request_id: Uuid, name: &str, payload: Option<Value>) -> Self {
        Self::create(request_id, IpcKind::Response, name, payload, None)
    }

    /// Successful response with a typed payload.
    pub fn response_with<T: Serialize>(
        request_id: Uuid,
        name: &str,
        payload: &T,
    ) -> Result<Self, ProtocolError> {
        Ok(Self::response(
            request_id,
            name,
            Some(serde_json::to_value(payload)?),
        ))
    }

    /// Successful response to `request` (same id, same name; `sys.ping` answers as `sys.pong`).
    pub fn reply_to(request: &IpcEnvelope, payload: Option<Value>) -> Self {
        Self::response(request.id, Self::response_name_for(&request.name), payload)
    }

    /// Successful typed response to `request`.
    pub fn reply_to_with<T: Serialize>(
        request: &IpcEnvelope,
        payload: &T,
    ) -> Result<Self, ProtocolError> {
        Ok(Self::reply_to(
            request,
            Some(serde_json::to_value(payload)?),
        ))
    }

    /// Event with a fresh id.
    pub fn event(name: &str, payload: Option<Value>) -> Self {
        Self::create(Uuid::new_v4(), IpcKind::Event, name, payload, None)
    }

    /// Event with a typed payload.
    pub fn event_with<T: Serialize>(name: &str, payload: &T) -> Result<Self, ProtocolError> {
        Ok(Self::event(name, Some(serde_json::to_value(payload)?)))
    }

    /// Failed response to `request_id`; payload is `None`.
    pub fn fail(request_id: Uuid, name: &str, error: IpcError) -> Self {
        Self::create(request_id, IpcKind::Response, name, None, Some(error))
    }

    /// Failed response to `request`.
    pub fn fail_for(request: &IpcEnvelope, error: IpcError) -> Self {
        Self::fail(request.id, Self::response_name_for(&request.name), error)
    }

    /// Replaces the sender timestamp (defaults to `Utc::now()` in the constructors).
    pub fn with_ts(mut self, ts: DateTime<Utc>) -> Self {
        self.ts = ts;
        self
    }

    /// `true` when this is a failed response.
    pub fn is_error(&self) -> bool {
        self.error.is_some()
    }

    /// `true` when `payload` holds a JSON object.
    pub fn has_payload(&self) -> bool {
        matches!(self.payload, Some(Value::Object(_)))
    }

    /// Deserializes `payload` as `T`; `Ok(None)` when absent or `null`.
    pub fn payload_as<T: DeserializeOwned>(&self) -> Result<Option<T>, ProtocolError> {
        object_as(self.payload.as_ref())
    }

    /// Deserializes `payload` as `T`, or `validation("payload", "required")` / `validation("payload",
    /// "<serde error>")` as an [`IpcError`].
    pub fn require_payload<T: DeserializeOwned>(&self) -> Result<T, IpcError> {
        match &self.payload {
            Some(v @ Value::Object(_)) => serde_json::from_value(v.clone())
                .map_err(|e| IpcError::validation("payload", &e.to_string())),
            _ => Err(IpcError::validation("payload", "required")),
        }
    }

    /// Structural validation of a decoded envelope (IPC_PROTOCOL.md §2). Returns the error a receiver
    /// should answer with, or `None` when the envelope is well-formed.
    pub fn validate(&self) -> Option<IpcError> {
        if !Self::is_version_supported(self.v) {
            return Some(IpcError::version_mismatch(Self::SUPPORTED_VERSIONS, self.v));
        }
        if self.id.is_nil() {
            return Some(IpcError::protocol_error(
                "Envelope id must be a non-empty UUID",
            ));
        }
        if !Self::is_valid_name(&self.name) {
            return Some(IpcError::protocol_error(
                "Envelope name must be '<domain>.<action>'",
            ));
        }
        if self.error.is_some() && self.kind != IpcKind::Response {
            return Some(IpcError::protocol_error(
                "Only responses may carry an error",
            ));
        }
        if !matches!(
            self.payload,
            None | Some(Value::Null) | Some(Value::Object(_))
        ) {
            return Some(IpcError::protocol_error(
                "Payload must be an object or null",
            ));
        }
        if self.error.is_some() && self.has_payload() {
            return Some(IpcError::protocol_error(
                "A failed response must not carry a payload",
            ));
        }
        None
    }

    /// Response name for a request name: identical except `sys.ping` → `sys.pong`.
    pub fn response_name_for(request_name: &str) -> &str {
        if request_name == names::sys::PING {
            names::sys::PONG
        } else {
            request_name
        }
    }

    /// `true` for `<domain>.<action>` where both parts are non-empty ASCII letters (≤ 64 chars).
    pub fn is_valid_name(name: &str) -> bool {
        if name.is_empty() || name.len() > 64 {
            return false;
        }
        match name.split_once('.') {
            Some((domain, action)) => {
                !domain.is_empty()
                    && !action.is_empty()
                    && domain.bytes().all(|b| b.is_ascii_alphabetic())
                    && action.bytes().all(|b| b.is_ascii_alphabetic())
            }
            None => false,
        }
    }
}

// ───────────────────────────── Framing ─────────────────────────────

/// Size of the little-endian length prefix.
pub const FRAME_HEADER_BYTES: usize = 4;

/// Encodes one envelope as `[u32 length LE][UTF-8 JSON]` (no BOM, no trailing newline).
pub fn encode_frame(envelope: &IpcEnvelope) -> Result<Vec<u8>, ProtocolError> {
    let mut out = vec![0u8; FRAME_HEADER_BYTES];
    serde_json::to_writer(&mut out, envelope)?;
    let len = out.len() - FRAME_HEADER_BYTES;
    if len > MAX_FRAME_BYTES {
        return Err(ProtocolError::FrameTooLarge {
            size: len,
            max: MAX_FRAME_BYTES,
        });
    }
    out[..FRAME_HEADER_BYTES].copy_from_slice(&(len as u32).to_le_bytes());
    Ok(out)
}

/// Decodes exactly one complete frame; errors on a short buffer, trailing bytes or an oversize length.
pub fn decode_frame(bytes: &[u8]) -> Result<IpcEnvelope, ProtocolError> {
    let len = frame_body_len(bytes)?;
    let total = FRAME_HEADER_BYTES + len;
    if bytes.len() < total {
        return Err(ProtocolError::Incomplete {
            needed: total,
            got: bytes.len(),
        });
    }
    if bytes.len() > total {
        return Err(ProtocolError::TrailingBytes(bytes.len() - total));
    }
    Ok(serde_json::from_slice(&bytes[FRAME_HEADER_BYTES..total])?)
}

/// Reads the length prefix; `Incomplete` when fewer than 4 bytes, `FrameTooLarge` beyond the limit.
fn frame_body_len(bytes: &[u8]) -> Result<usize, ProtocolError> {
    if bytes.len() < FRAME_HEADER_BYTES {
        return Err(ProtocolError::Incomplete {
            needed: FRAME_HEADER_BYTES,
            got: bytes.len(),
        });
    }
    let len = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]) as usize;
    if len > MAX_FRAME_BYTES {
        return Err(ProtocolError::FrameTooLarge {
            size: len,
            max: MAX_FRAME_BYTES,
        });
    }
    Ok(len)
}

/// Incremental frame decoder for byte-stream transports: feed arbitrary chunks with [`push`](Self::push)
/// and drain complete envelopes with [`next_frame`](Self::next_frame).
///
/// A JSON error consumes the offending frame (the length prefix still delimits it), so the caller can
/// answer `protocolError` and keep reading. `FrameTooLarge` leaves the buffer untouched: the stream is
/// unrecoverable and the connection must be closed (IPC_PROTOCOL.md §1).
#[derive(Debug, Default)]
pub struct FrameReader {
    buf: Vec<u8>,
    pos: usize,
}

impl FrameReader {
    pub fn new() -> Self {
        Self::default()
    }

    /// Appends received bytes.
    pub fn push(&mut self, bytes: &[u8]) {
        if self.pos > 0 && self.pos >= self.buf.len() / 2 {
            self.buf.drain(..self.pos);
            self.pos = 0;
        }
        self.buf.extend_from_slice(bytes);
    }

    /// Next complete envelope, `Ok(None)` when more bytes are needed.
    pub fn next_frame(&mut self) -> Result<Option<IpcEnvelope>, ProtocolError> {
        let pending = &self.buf[self.pos..];
        let len = match frame_body_len(pending) {
            Ok(len) => len,
            Err(ProtocolError::Incomplete { .. }) => return Ok(None),
            Err(e) => return Err(e),
        };
        let total = FRAME_HEADER_BYTES + len;
        if pending.len() < total {
            return Ok(None);
        }
        let body = &pending[FRAME_HEADER_BYTES..total];
        let parsed = serde_json::from_slice::<IpcEnvelope>(body);
        self.pos += total;
        Ok(Some(parsed?))
    }

    /// Bytes buffered but not yet consumed.
    pub fn pending(&self) -> usize {
        self.buf.len() - self.pos
    }

    /// Discards everything buffered.
    pub fn clear(&mut self) {
        self.buf.clear();
        self.pos = 0;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::{SessionStartRequest, SysPingRequest};
    use crate::error::{assert_wire, ErrorCode, VersionMismatchDetails};
    use chrono::TimeZone;

    fn ts() -> DateTime<Utc> {
        Utc.with_ymd_and_hms(2026, 9, 21, 10, 15, 30).unwrap() + chrono::Duration::milliseconds(123)
    }

    const REQ_JSON: &str = r#"{"v":1,"id":"6f1d2c4e-1b3a-4a7c-9f7d-0e6f2b5a9c11","kind":"request","name":"session.start","ts":"2026-09-21T10:15:30.123Z","payload":{"tariffId":"b1a5b6b4-3f6e-4b7f-8c26-1d0e2e5c9a10","prepaid":true,"minutes":60},"error":null}"#;

    fn sample_request() -> IpcEnvelope {
        let payload = SessionStartRequest {
            tariff_id: Uuid::parse_str("b1a5b6b4-3f6e-4b7f-8c26-1d0e2e5c9a10").unwrap(),
            prepaid: true,
            minutes: Some(60),
        };
        IpcEnvelope {
            id: Uuid::parse_str("6f1d2c4e-1b3a-4a7c-9f7d-0e6f2b5a9c11").unwrap(),
            ..IpcEnvelope::request_with(names::session::START, &payload)
                .unwrap()
                .with_ts(ts())
        }
    }

    #[test]
    fn enum_wire_values() {
        assert_wire(IpcKind::ALL, &["request", "response", "event"]);
    }

    #[test]
    fn envelope_json_matches_ipc_protocol_example() {
        let req = sample_request();
        assert_eq!(serde_json::to_string(&req).unwrap(), REQ_JSON);
        let back: IpcEnvelope = serde_json::from_str(REQ_JSON).unwrap();
        assert_eq!(back, req);
        assert!(back.has_payload());
        assert!(!back.is_error());
        let p: SessionStartRequest = back.require_payload().unwrap();
        assert_eq!(p.minutes, Some(60));
        assert_eq!(back.validate(), None);
        // Missing payload/error keys are tolerated on read.
        let minimal: IpcEnvelope = serde_json::from_str(r#"{"v":1,"id":"6f1d2c4e-1b3a-4a7c-9f7d-0e6f2b5a9c11","kind":"request","name":"auth.status","ts":"2026-09-21T10:15:30Z"}"#).unwrap();
        assert_eq!(minimal.payload, None);
        assert_eq!(minimal.payload_as::<SessionStartRequest>().unwrap(), None);
        assert_eq!(
            minimal
                .require_payload::<SessionStartRequest>()
                .unwrap_err()
                .code,
            ErrorCode::Validation
        );
    }

    #[test]
    fn responses_and_failures() {
        let req = sample_request();
        let ok = IpcEnvelope::reply_to(&req, None);
        assert_eq!(ok.id, req.id);
        assert_eq!(ok.kind, IpcKind::Response);
        assert_eq!(ok.name, "session.start");
        assert_eq!(
            serde_json::to_string(&ok.with_ts(ts())).unwrap(),
            r#"{"v":1,"id":"6f1d2c4e-1b3a-4a7c-9f7d-0e6f2b5a9c11","kind":"response","name":"session.start","ts":"2026-09-21T10:15:30.123Z","payload":null,"error":null}"#
        );

        let failed = IpcEnvelope::fail_for(&req, IpcError::session_already_active()).with_ts(ts());
        assert!(failed.is_error());
        assert_eq!(failed.validate(), None);
        assert_eq!(
            serde_json::to_string(&failed).unwrap(),
            r#"{"v":1,"id":"6f1d2c4e-1b3a-4a7c-9f7d-0e6f2b5a9c11","kind":"response","name":"session.start","ts":"2026-09-21T10:15:30.123Z","payload":null,"error":{"code":"sessionAlreadyActive","message":"A session is already active","details":null}}"#
        );

        let ping = IpcEnvelope::request_with(
            names::sys::PING,
            &SysPingRequest {
                seq: 1,
                sent_at: ts(),
            },
        )
        .unwrap();
        let pong = IpcEnvelope::reply_to(&ping, None);
        assert_eq!(pong.name, names::sys::PONG);
        assert_eq!(IpcEnvelope::response_name_for("games.list"), "games.list");

        let ev = IpcEnvelope::event(
            names::events::AUTH_EXPIRED,
            Some(serde_json::json!({ "reason": "revoked" })),
        );
        assert_eq!(ev.kind, IpcKind::Event);
        assert_eq!(ev.validate(), None);
        assert_ne!(ev.id, req.id);
    }

    #[test]
    fn validate_rejects_malformed_envelopes() {
        let good = sample_request();
        let bad_version = IpcEnvelope {
            v: 2,
            ..good.clone()
        };
        let err = bad_version.validate().unwrap();
        assert_eq!(err.code, ErrorCode::VersionMismatch);
        let d: VersionMismatchDetails = err.details_as().unwrap().unwrap();
        assert_eq!(
            d,
            VersionMismatchDetails {
                supported: vec![1],
                got: 2
            }
        );
        // `v` is a C# `int`: a negative major still decodes and is answered with versionMismatch, not protocolError.
        let negative: IpcEnvelope =
            serde_json::from_str(&REQ_JSON.replace(r#""v":1"#, r#""v":-1"#)).unwrap();
        assert_eq!(
            negative.validate().unwrap().code,
            ErrorCode::VersionMismatch
        );
        assert_eq!(
            IpcEnvelope {
                id: Uuid::nil(),
                ..good.clone()
            }
            .validate()
            .unwrap()
            .code,
            ErrorCode::ProtocolError
        );
        assert_eq!(
            IpcEnvelope {
                name: "nodot".into(),
                ..good.clone()
            }
            .validate()
            .unwrap()
            .code,
            ErrorCode::ProtocolError
        );
        assert_eq!(
            IpcEnvelope {
                payload: Some(serde_json::json!([1])),
                ..good.clone()
            }
            .validate()
            .unwrap()
            .code,
            ErrorCode::ProtocolError
        );
        let err_on_request = IpcEnvelope {
            error: Some(IpcError::timeout(None)),
            ..good.clone()
        };
        assert_eq!(
            err_on_request.validate().unwrap().message,
            "Only responses may carry an error"
        );
        let err_with_payload = IpcEnvelope {
            kind: IpcKind::Response,
            error: Some(IpcError::timeout(None)),
            ..good.clone()
        };
        assert_eq!(
            err_with_payload.validate().unwrap().message,
            "A failed response must not carry a payload"
        );
        assert_eq!(
            IpcEnvelope {
                payload: Some(Value::Null),
                ..good
            }
            .validate(),
            None
        );

        assert!(IpcEnvelope::is_valid_name("auth.hello"));
        assert!(IpcEnvelope::is_valid_name("sys.ackAdminMessage"));
        assert!(!IpcEnvelope::is_valid_name(""));
        assert!(!IpcEnvelope::is_valid_name("auth"));
        assert!(!IpcEnvelope::is_valid_name(".hello"));
        assert!(!IpcEnvelope::is_valid_name("auth."));
        assert!(!IpcEnvelope::is_valid_name("a.b.c"));
        assert!(!IpcEnvelope::is_valid_name("auth.hello2"));
        assert!(!IpcEnvelope::is_valid_name(&format!(
            "{}.{}",
            "a".repeat(40),
            "b".repeat(30)
        )));
    }

    #[test]
    fn frame_round_trip() {
        let req = sample_request();
        let frame = encode_frame(&req).unwrap();
        let body = REQ_JSON.as_bytes();
        assert_eq!(&frame[..4], (body.len() as u32).to_le_bytes());
        assert_eq!(&frame[4..], body);
        assert_eq!(decode_frame(&frame).unwrap(), req);

        assert!(matches!(
            decode_frame(&frame[..3]),
            Err(ProtocolError::Incomplete { needed: 4, got: 3 })
        ));
        assert!(matches!(
            decode_frame(&frame[..10]),
            Err(ProtocolError::Incomplete { .. })
        ));
        let mut trailing = frame.clone();
        trailing.push(b'x');
        assert!(matches!(
            decode_frame(&trailing),
            Err(ProtocolError::TrailingBytes(1))
        ));
        let mut huge = frame.clone();
        huge[..4].copy_from_slice(&((MAX_FRAME_BYTES as u32) + 1).to_le_bytes());
        assert!(matches!(
            decode_frame(&huge),
            Err(ProtocolError::FrameTooLarge { .. })
        ));
        let mut garbage = frame.clone();
        garbage[4] = b'x';
        assert!(matches!(
            decode_frame(&garbage),
            Err(ProtocolError::Json(_))
        ));

        let oversize = IpcEnvelope::request(
            "x.y",
            Some(serde_json::json!({ "blob": "a".repeat(MAX_FRAME_BYTES) })),
        );
        assert!(matches!(
            encode_frame(&oversize),
            Err(ProtocolError::FrameTooLarge { .. })
        ));
    }

    #[test]
    fn frame_reader_reassembles_partial_chunks() {
        let a = sample_request();
        let b = IpcEnvelope::fail_for(&a, IpcError::timeout(None)).with_ts(ts());
        let mut stream = encode_frame(&a).unwrap();
        stream.extend(encode_frame(&b).unwrap());

        let mut reader = FrameReader::new();
        let mut out = Vec::new();
        for chunk in stream.chunks(7) {
            reader.push(chunk);
            while let Some(env) = reader.next_frame().unwrap() {
                out.push(env);
            }
        }
        assert_eq!(out, vec![a.clone(), b.clone()]);
        assert_eq!(reader.pending(), 0);

        // Everything in one push, plus a partial third frame.
        let mut reader = FrameReader::new();
        let third = encode_frame(&a).unwrap();
        reader.push(&stream);
        reader.push(&third[..third.len() - 1]);
        assert_eq!(reader.next_frame().unwrap(), Some(a.clone()));
        assert_eq!(reader.next_frame().unwrap(), Some(b));
        assert_eq!(reader.next_frame().unwrap(), None);
        assert_eq!(reader.pending(), third.len() - 1);
        reader.push(&third[third.len() - 1..]);
        assert_eq!(reader.next_frame().unwrap(), Some(a.clone()));
        assert_eq!(reader.next_frame().unwrap(), None);

        // A malformed frame is consumed; the stream continues with the next one.
        let mut reader = FrameReader::new();
        let mut bad = encode_frame(&a).unwrap();
        bad[4] = b'{';
        bad[5] = b'x';
        reader.push(&bad);
        reader.push(&third);
        assert!(matches!(reader.next_frame(), Err(ProtocolError::Json(_))));
        assert_eq!(reader.next_frame().unwrap(), Some(a));
        assert_eq!(reader.pending(), 0);

        // Oversize length prefix is fatal and leaves the buffer untouched.
        let mut reader = FrameReader::new();
        reader.push(&(MAX_FRAME_BYTES as u32 + 1).to_le_bytes());
        assert!(matches!(
            reader.next_frame(),
            Err(ProtocolError::FrameTooLarge { .. })
        ));
        assert_eq!(reader.pending(), 4);
        reader.clear();
        assert_eq!(reader.pending(), 0);
    }
}
// ---- END MANUAL ----
