using System.Text.Json;
using System.Text.Json.Serialization;
using ClubShell.Contracts.Errors;
using ClubShell.Contracts.Serialization;

namespace ClubShell.Contracts.Ipc;

/// <summary>Envelope kind (IPC_PROTOCOL.md §2).</summary>
[JsonConverter(typeof(CamelCaseEnumConverter<IpcKind>))]
public enum IpcKind
{
    /// <summary>Shell → Agent request; exactly one <see cref="Response"/> with the same id follows.</summary>
    Request,

    /// <summary>Agent → Shell reply; copies the request id.</summary>
    Response,

    /// <summary>Agent → Shell notification; fresh id, never answered.</summary>
    Event,
}

/// <summary>
/// One pipe frame (IPC_PROTOCOL.md §2). Serialized as
/// <c>{ "v", "id", "kind", "name", "ts", "payload", "error" }</c>; <c>payload</c> and <c>error</c> keys are always present.
/// </summary>
/// <param name="V">Protocol major. Receivers reject unsupported values with <see cref="ErrorCode.VersionMismatch"/>.</param>
/// <param name="Id">Request id generated by the sender; a response copies it; events use a fresh id.</param>
/// <param name="Kind">Envelope kind.</param>
/// <param name="Name">Message name <c>&lt;domain&gt;.&lt;action&gt;</c>; a response repeats the request name (except <c>sys.ping</c> → <c>sys.pong</c>).</param>
/// <param name="Ts">Sender wall clock (UTC). Informational only, never used for ordering.</param>
/// <param name="Payload">Body; <see langword="null"/> when the message carries no data. Never an array or scalar at top level.</param>
/// <param name="Error">Non-null only on a response; when set, <paramref name="Payload"/> is <see langword="null"/>.</param>
public sealed record IpcEnvelope(
    int V,
    Guid Id,
    IpcKind Kind,
    string Name,
    DateTimeOffset Ts,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.Never)] JsonElement? Payload,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.Never)] IpcError? Error)
{
    /// <summary>Protocol major implemented by this library.</summary>
    public const int CurrentVersion = 1;

    /// <summary>Maximum JSON frame size in bytes (excluding the 4-byte length prefix).</summary>
    public const int MaxFrameBytes = 4 * 1024 * 1024;

    /// <summary><see langword="true"/> when this is a failed response.</summary>
    [JsonIgnore]
    public bool IsError => Error is not null;

    /// <summary><see langword="true"/> when <see cref="Payload"/> holds a JSON object.</summary>
    [JsonIgnore]
    public bool HasPayload => Payload is { ValueKind: JsonValueKind.Object };

    /// <summary><see langword="true"/> when protocol major <paramref name="v"/> is accepted by this implementation.</summary>
    public static bool IsVersionSupported(int v) => v == CurrentVersion;

    /// <summary>Supported protocol majors, for <see cref="VersionMismatchDetails"/>.</summary>
    public static IReadOnlyList<int> SupportedVersions { get; } = new[] { CurrentVersion };

    /// <summary>Builds a request with a fresh id.</summary>
    public static IpcEnvelope Request(string name, JsonElement? payload = null, DateTimeOffset? ts = null) =>
        Create(Guid.NewGuid(), IpcKind.Request, name, payload, null, ts);

    /// <summary>Builds a request with a typed payload serialized through <see cref="ContractsJsonContext"/>.</summary>
    /// <remarks>
    /// The typed overloads call <see cref="Create"/> directly: a <see cref="JsonElement"/> argument would otherwise bind to the
    /// generic overload (identity conversion beats the lift to <c>JsonElement?</c>) and recurse forever.
    /// </remarks>
    public static IpcEnvelope Request<TPayload>(string name, TPayload payload, DateTimeOffset? ts = null) =>
        Create(Guid.NewGuid(), IpcKind.Request, name, JsonDefaults.ToElement(payload), null, ts);

    /// <summary>Builds a successful response to <paramref name="requestId"/>.</summary>
    public static IpcEnvelope Response(Guid requestId, string name, JsonElement? payload = null, DateTimeOffset? ts = null) =>
        Create(requestId, IpcKind.Response, name, payload, null, ts);

    /// <summary>Builds a successful response with a typed payload.</summary>
    public static IpcEnvelope Response<TPayload>(Guid requestId, string name, TPayload payload, DateTimeOffset? ts = null) =>
        Create(requestId, IpcKind.Response, name, JsonDefaults.ToElement(payload), null, ts);

    /// <summary>Builds a successful response to <paramref name="request"/> (same id, same name; <c>sys.ping</c> answers as <c>sys.pong</c>).</summary>
    public static IpcEnvelope ReplyTo(IpcEnvelope request, JsonElement? payload = null, DateTimeOffset? ts = null)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Response(request.Id, ResponseNameFor(request.Name), payload, ts);
    }

    /// <summary>Builds a successful typed response to <paramref name="request"/>.</summary>
    public static IpcEnvelope ReplyTo<TPayload>(IpcEnvelope request, TPayload payload, DateTimeOffset? ts = null)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Create(request.Id, IpcKind.Response, ResponseNameFor(request.Name), JsonDefaults.ToElement(payload), null, ts);
    }

    /// <summary>Builds an event with a fresh id.</summary>
    public static IpcEnvelope Event(string name, JsonElement? payload = null, DateTimeOffset? ts = null) =>
        Create(Guid.NewGuid(), IpcKind.Event, name, payload, null, ts);

    /// <summary>Builds an event with a typed payload.</summary>
    public static IpcEnvelope Event<TPayload>(string name, TPayload payload, DateTimeOffset? ts = null) =>
        Create(Guid.NewGuid(), IpcKind.Event, name, JsonDefaults.ToElement(payload), null, ts);

    /// <summary>Builds a failed response to <paramref name="requestId"/>; payload is <see langword="null"/>.</summary>
    public static IpcEnvelope Fail(Guid requestId, string name, IpcError error, DateTimeOffset? ts = null)
    {
        ArgumentNullException.ThrowIfNull(error);
        return Create(requestId, IpcKind.Response, name, null, error, ts);
    }

    /// <summary>Builds a failed response to <paramref name="request"/>.</summary>
    public static IpcEnvelope Fail(IpcEnvelope request, IpcError error, DateTimeOffset? ts = null)
    {
        ArgumentNullException.ThrowIfNull(request);
        return Fail(request.Id, ResponseNameFor(request.Name), error, ts);
    }

    /// <summary>Deserializes <see cref="Payload"/> as <typeparamref name="TPayload"/>; <see langword="null"/> when the payload is absent.</summary>
    public TPayload? PayloadAs<TPayload>() =>
        Payload is { ValueKind: not JsonValueKind.Null and not JsonValueKind.Undefined } p
            ? JsonDefaults.FromElement<TPayload>(p)
            : default;

    /// <summary>Deserializes <see cref="Payload"/> as <typeparamref name="TPayload"/> or throws <see cref="IpcException"/>(<see cref="ErrorCode.Validation"/>) when absent.</summary>
    public TPayload RequirePayload<TPayload>()
    {
        if (!HasPayload)
        {
            throw new IpcException(IpcError.Validation("payload", "required"));
        }

        var value = JsonDefaults.FromElement<TPayload>(Payload.GetValueOrDefault());
        if (value is null)
        {
            throw new IpcException(IpcError.Validation("payload", "required"));
        }

        return value;
    }

    /// <summary>
    /// Structural validation of a decoded envelope (rules of IPC_PROTOCOL.md §2). Returns the error a receiver
    /// should answer with, or <see langword="null"/> when the envelope is well-formed.
    /// </summary>
    public IpcError? Validate()
    {
        if (!IsVersionSupported(V))
        {
            return IpcError.VersionMismatch(SupportedVersions, V);
        }

        if (Id == Guid.Empty)
        {
            return IpcError.ProtocolError("Envelope id must be a non-empty UUID");
        }

        if (!IsValidName(Name))
        {
            return IpcError.ProtocolError("Envelope name must be '<domain>.<action>'");
        }

        if (Kind is not (IpcKind.Request or IpcKind.Response or IpcKind.Event))
        {
            return IpcError.ProtocolError("Unknown envelope kind");
        }

        if (Error is not null && Kind != IpcKind.Response)
        {
            return IpcError.ProtocolError("Only responses may carry an error");
        }

        if (Payload is { ValueKind: not JsonValueKind.Null and not JsonValueKind.Undefined and not JsonValueKind.Object })
        {
            return IpcError.ProtocolError("Payload must be an object or null");
        }

        if (Error is not null && HasPayload)
        {
            return IpcError.ProtocolError("A failed response must not carry a payload");
        }

        return null;
    }

    /// <summary>Response name for a request name: identical except <c>sys.ping</c> → <c>sys.pong</c>.</summary>
    public static string ResponseNameFor(string requestName) =>
        string.Equals(requestName, IpcMessages.Sys.Ping, StringComparison.Ordinal) ? IpcMessages.Sys.Pong : requestName;

    /// <summary><see langword="true"/> for <c>&lt;domain&gt;.&lt;action&gt;</c> where both parts are non-empty ASCII letters.</summary>
    public static bool IsValidName(string? name)
    {
        if (string.IsNullOrEmpty(name) || name.Length > 64)
        {
            return false;
        }

        var dot = name.IndexOf('.', StringComparison.Ordinal);
        if (dot <= 0 || dot == name.Length - 1 || name.IndexOf('.', dot + 1) >= 0)
        {
            return false;
        }

        foreach (var c in name)
        {
            if (c != '.' && !char.IsAsciiLetter(c))
            {
                return false;
            }
        }

        return true;
    }

    private static IpcEnvelope Create(Guid id, IpcKind kind, string name, JsonElement? payload, IpcError? error, DateTimeOffset? ts)
    {
        ArgumentException.ThrowIfNullOrEmpty(name);
        return new IpcEnvelope(CurrentVersion, id, kind, name, ts ?? DateTimeOffset.UtcNow, payload, error);
    }
}
