// <auto-generated> by tools/ContractsGen from ClubShell.Contracts v1.0.0 — edit only inside MANUAL blocks

import type { NotificationLevel } from './events.js';
import type { AntiCheatKind, App, GamesSort, LauncherType, Resolution, RunningGame } from './games.js';
import type { AgentServerConfig, ConnectivityState, HardwareInfo, Pc, PcMetrics, PcStatus } from './pc.js';
import type { Session, SessionEndReason, SessionState } from './session.js';
import type { Order, OrderLineRequest, Product, ProductCategory } from './shop.js';
import type {
  Achievement,
  AuthKind,
  Booking,
  ChatMessage,
  LeaderboardEntry,
  Locale,
  Seat,
  Tournament,
  TournamentState,
  User,
} from './user.js';
import type { Money, Tariff, TopupProvider, TransactionType } from './wallet.js';

/** Opaque JSON object (`JsonElement` in C#). */
export type JsonObject = Record<string, unknown>;

/**
 * Error codes shared verbatim by the IPC protocol (`IpcError.code`), the central server REST error envelope
 * (`error.code`) and the Tauri `ShellError.code`. Wire literal is camelCase (`CamelCaseEnumConverter`). See
 * IPC_PROTOCOL.md §5.
 */
export const ErrorCode = {
  /** Not authenticated / bad token / bad credentials (HTTP 401). */
  Unauthorized: 'unauthorized',
  /** Authenticated but not allowed: role, SID, capability (HTTP 403). */
  Forbidden: 'forbidden',
  /** Entity or message name unknown (HTTP 404). */
  NotFound: 'notFound',
  /** Payload invalid; `details.field` / `details.reason` (HTTP 400). */
  Validation: 'validation',
  /** State conflict: duplicate, out of stock, already joined (HTTP 409). */
  Conflict: 'conflict',
  /** Balance too low; `details: { required: Money, available: Money }` (HTTP 402). */
  InsufficientFunds: 'insufficientFunds',
  /** Operation needs an active/paused session (HTTP 409). */
  SessionNotActive: 'sessionNotActive',
  /** `session.start` while a session already exists (HTTP 409). */
  SessionAlreadyActive: 'sessionAlreadyActive',
  /** Game not installed or install path missing (HTTP 409). */
  GameNotInstalled: 'gameNotInstalled',
  /** Launcher error; `details: { stage, exitCode?, stderr? }` (HTTP 500). */
  GameLaunchFailed: 'gameLaunchFailed',
  /** No free pooled account (HTTP 409). */
  AccountPoolExhausted: 'accountPoolExhausted',
  /** Anti-cheat prerequisite failed; `details: { kind, reason }` (HTTP 403). */
  AntiCheatBlocked: 'antiCheatBlocked',
  /** Blocked by policy; `details: { rule }` (HTTP 403). */
  PolicyDenied: 'policyDenied',
  /** Agent has no server connection and the operation cannot be served from cache (HTTP 503). */
  AgentOffline: 'agentOffline',
  /** Server returned 5xx or the circuit breaker is open (HTTP 503). */
  ServerUnavailable: 'serverUnavailable',
  /** Upstream or launch timeout (HTTP 504). */
  Timeout: 'timeout',
  /** Too many requests; `details.retryAfterSec` (HTTP 429). */
  RateLimited: 'rateLimited',
  /** Unexpected exception; `details.traceId` (HTTP 500). */
  Internal: 'internal',
  /** Envelope / framing violation (HTTP 400). */
  ProtocolError: 'protocolError',
  /** Protocol or application version unsupported; `details: { supported: [..], got }` (HTTP 426). */
  VersionMismatch: 'versionMismatch',
} as const;
/**
 * Error codes shared verbatim by the IPC protocol (`IpcError.code`), the central server REST error envelope
 * (`error.code`) and the Tauri `ShellError.code`. Wire literal is camelCase (`CamelCaseEnumConverter`). See
 * IPC_PROTOCOL.md §5.
 */
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Central-server error object. Maps 1:1 onto `IpcError` via `ServerError.ToIpcError`. */
export interface ServerError {
  /** Error code. */
  code: ErrorCode;
  /** Human-readable English message. */
  message: string;
  /** Structured extra data; key always present (`null` when none). */
  details: JsonObject | null;
  /** Server trace id (echo of `X-Trace-Id`). */
  traceId: string;
}

/** Body of every non-2xx central-server response: `{ "error": ServerError }` (SERVER_API.md §3). */
export interface ServerErrorEnvelope {
  /** The error. */
  error: ServerError;
}

/**
 * Agent capabilities advertised in `AuthHelloResponse.Capabilities`; the Shell hides features whose capability is
 * absent.
 */
export const AgentCapabilities = {
  /** Account-pool credential injection. */
  AccountPool: 'accountPool',
  /** Cloud save sync. */
  CloudSave: 'cloudSave',
  /** Remote control by admins. */
  RemoteControl: 'remoteControl',
  /** Screen capture. */
  ScreenCapture: 'screenCapture',
  /** On-screen keyboard allowed. */
  VirtualKeyboard: 'virtualKeyboard',
  /** Wake-on-LAN relay. */
  Wol: 'wol',
  /** Offline mode. */
  Offline: 'offline',
  /** Shop. */
  Shop: 'shop',
  /** Chat. */
  Chat: 'chat',
  /** Booking. */
  Booking: 'booking',
  /** Tournaments. */
  Tournaments: 'tournaments',
} as const;
/** One of the {@link AgentCapabilities} values. */
export type AgentCapability = (typeof AgentCapabilities)[keyof typeof AgentCapabilities];

/** `details` for `ErrorCode.AntiCheatBlocked`. */
export interface AntiCheatBlockedDetails {
  /** Anti-cheat subsystem. */
  kind: AntiCheatKind;
  /** Check that failed, e.g. `driverMissing`, `secureBootOff`. */
  reason: string;
}

/** Request of `apps.launch`. */
export interface AppsLaunchRequest {
  /** App id. */
  appId: string;
  /** Extra command line. */
  args?: string | null;
}

/** Response of `apps.launch`. */
export interface AppsLaunchResponse {
  /** Always `true`. */
  ok: boolean;
  /** Process id. */
  pid: number;
  /** Launch time. */
  startedAt: string;
}

/** Response of `apps.list` and `GET /apps`. */
export interface AppsListResponse {
  /** Apps. */
  items: App[];
}

/** Request of `auth.hello`. */
export interface AuthHelloRequest {
  /** 64 hex chars from `secure\shell.token`; compared in constant time. */
  shellToken: string;
  /** Shell semver. */
  shellVersion: string;
  /** Shell process id. */
  pid: number;
  /** Windows session id. */
  wtsSessionId: number;
  /** Current UI locale. */
  locale: Locale;
  /** Shell capabilities (`ShellCapabilities`). */
  capabilities: string[];
}

/** Response of `auth.hello`. */
export interface AuthHelloResponse {
  /** Agent semver. */
  agentVersion: string;
  /** IPC protocol major (`IpcEnvelope.CurrentVersion`). */
  protocol: number;
  /** PC id. */
  pcId: string;
  /** PC name. */
  pcName: string;
  /** Zone. */
  zone: string;
  /** Server reachable. */
  serverOnline: boolean;
  /** Applied policy version. */
  policyVersion: number;
  /** Agent's best estimate of server time. */
  serverTime: string;
  /** Agent capabilities (`AgentCapabilities`). */
  capabilities: string[];
  /** Kiosk Windows account name. */
  kioskUser: string;
}

/** Request of `auth.login` (subset of `AuthRequest` without PC identity). Secrets are never logged. */
export interface AuthLoginRequest {
  /** Method. */
  kind: AuthKind;
  /** Login name (`AuthKind.Password`). */
  username?: string | null;
  /** Password (`AuthKind.Password`). */
  password?: string | null;
  /** QR token (`AuthKind.Qr`). */
  qrToken?: string | null;
  /** Card id (`AuthKind.Card`). */
  cardId?: string | null;
  /** One-time token (`AuthKind.Token`). */
  token?: string | null;
}

/** Response of `auth.login`. */
export interface AuthLoginResponse {
  /** Authenticated user. */
  user: User;
  /** Existing session bound to this user on this PC, when any. */
  session?: Session | null;
  /** User access token expiry (token is Agent-held). */
  expiresAt: string;
  /** `ConnectivityState.Offline` when validated from cache. */
  mode: ConnectivityState;
}

/** Request of `auth.logout`. */
export interface AuthLogoutRequest {
  /** Why; defaults to `SessionEndReason.User`. Only `user`, `idle`, `admin` are valid from the Shell. */
  reason?: SessionEndReason | null;
}

/** Response of `auth.logout`. */
export interface AuthLogoutResponse {
  /** Always `true`. */
  ok: boolean;
  /** Whether an active session was ended first. */
  sessionEnded: boolean;
  /** The ended session, when any. */
  session?: Session | null;
}

/** Response of `auth.status`. */
export interface AuthStatusResponse {
  /** Whether a user is logged in. */
  authenticated: boolean;
  /** Connectivity. */
  mode: ConnectivityState;
  /** Logged-in user. */
  user?: User | null;
  /** Current session. */
  session?: Session | null;
  /** User token expiry. */
  expiresAt?: string | null;
}

/** Request of `booking.cancel`. */
export interface BookingCancelRequest {
  /** Booking id. */
  bookingId: string;
}

/** Request of `booking.reserve`. */
export interface BookingReserveRequest {
  /** PC. */
  pcId: string;
  /** Start (slot-aligned, future). */
  from: string;
  /** End. */
  to: string;
}

/** Request of `booking.seats`. */
export interface BookingSeatsRequest {
  /** Club-local date. */
  date: string;
}

/**
 * Response of `booking.seats` and `GET /booking/seats`. Other users' bookings are anonymized (`userId` = `Guid.Empty`).
 */
export interface BookingSeatsResponse {
  /** Date. */
  date: string;
  /** Seat map. */
  seats: Seat[];
  /** All bookings of that day. */
  bookings: Booking[];
  /** Slot granularity. */
  slotMinutes: number;
  /** Club opening time (REST only). */
  openFrom?: string | null;
  /** Club closing time (REST only). */
  openTo?: string | null;
}

/** Category of a `sys.callAdmin` ticket. */
export const CallAdminCategory = {
  /** General help. */
  Help: 'help',
  /** Technical problem. */
  Technical: 'technical',
  /** Shop order issue. */
  Order: 'order',
  /** Anything else. */
  Other: 'other',
} as const;
/** Category of a `sys.callAdmin` ticket. */
export type CallAdminCategory = (typeof CallAdminCategory)[keyof typeof CallAdminCategory];

/** Request of `chat.history`. */
export interface ChatHistoryRequest {
  /** Room; defaults to `pc:<pcId>`. */
  roomId?: string | null;
  /** Return messages older than this message id. */
  before?: string | null;
  /** Page size (default 50, max 200). */
  limit?: number | null;
}
/** Default page size. */
export const CHAT_HISTORY_DEFAULT_LIMIT = 50;
/** Maximum page size. */
export const CHAT_HISTORY_MAX_LIMIT = 200;

/** Response of `chat.history` and `GET /chat/{roomId}/messages`. */
export interface ChatHistoryResponse {
  /** Room. */
  roomId: string;
  /** Messages, oldest first. */
  items: ChatMessage[];
  /** Older messages exist. */
  hasMore: boolean;
  /** Unread count in the room. */
  unread: number;
}

/** Request of `chat.markRead`. */
export interface ChatMarkReadRequest {
  /** Mark up to and including this message. */
  upToMessageId: string;
  /** Room; defaults to `pc:<pcId>`. */
  roomId?: string | null;
}

/** Response of `chat.markRead` and `POST /chat/{roomId}/read`. */
export interface ChatMarkReadResponse {
  /** Room. */
  roomId: string;
  /** Remaining unread count. */
  unread: number;
}

/** Request of `chat.send`. */
export interface ChatSendRequest {
  /** Text (1–2000 chars). */
  text: string;
  /** Client-generated key forwarded as `Idempotency-Key`. */
  idempotencyKey: string;
  /** Room; defaults to `pc:<pcId>`. */
  roomId?: string | null;
}

/** Severity of a client-side error forwarded via `sys.logClientError`. */
export const ClientErrorLevel = {
  /** Warning. */
  Warn: 'warn',
  /** Error. */
  Error: 'error',
} as const;
/** Severity of a client-side error forwarded via `sys.logClientError`. */
export type ClientErrorLevel = (typeof ClientErrorLevel)[keyof typeof ClientErrorLevel];

/** Installed component versions. */
export interface ComponentVersions {
  /** Agent semver. */
  agent: string;
  /** Shell semver. */
  shell: string;
}

/** Request of `games.get`. */
export interface GamesGetRequest {
  /** Game id. */
  gameId: string;
}

/** Request of `games.installStatus`. */
export interface GamesInstallStatusRequest {
  /** Game id. */
  gameId: string;
}

/** Request of `games.kill`; at least one of `gameId`/`pid`, none = kill all. */
export interface GamesKillRequest {
  /** Game to kill. */
  gameId?: string | null;
  /** Process to kill. */
  pid?: number | null;
  /** Terminate immediately. */
  force?: boolean | null;
}

/** Response of `games.kill` and result of the `killGame` server command. */
export interface GamesKillResponse {
  /** Number of processes killed. */
  killed: number;
  /** Process ids killed. */
  pids: number[];
}

/** Request of `games.launch`; the Agent fills session/user/timeout to build a `LaunchRequest`. */
export interface GamesLaunchRequest {
  /** Game id. */
  gameId: string;
  /** Defaults to `Game.RequiresAccount`. */
  useAccountPool?: boolean | null;
  /** Extra command line (appended after policy sanitization). */
  extraArgs?: string | null;
  /** Requested resolution. */
  resolution?: Resolution | null;
}

/** Request of `games.list`. */
export interface GamesListRequest {
  /** Filter by category. */
  category?: string | null;
  /** Free-text search. */
  search?: string | null;
  /** Only installed games. */
  installedOnly?: boolean | null;
  /** Filter by launcher. */
  launcher?: LauncherType | null;
  /** Sort order (default popularity). */
  sort?: GamesSort | null;
  /** 1-based page (default 1). */
  page?: number | null;
  /** Page size (default 100, max 500). */
  pageSize?: number | null;
}
/** Default page size. */
export const GAMES_LIST_DEFAULT_PAGE_SIZE = 100;
/** Maximum page size. */
export const GAMES_LIST_MAX_PAGE_SIZE = 500;

/** Response of `games.running`. */
export interface GamesRunningResponse {
  /** Running games. */
  items: RunningGame[];
}

/** `details` for `ErrorCode.InsufficientFunds`. */
export interface InsufficientFundsDetails {
  /** Amount required by the operation. */
  required: Money;
  /** Amount currently available. */
  available: Money;
}

/**
 * Error carried by an IPC response envelope (IPC_PROTOCOL.md §2) and by `game.stateChanged` / `update.progress` events.
 * `details` is always present on the wire (`null` when empty).
 */
export interface IpcError {
  /** Error code. */
  code: ErrorCode;
  /** Human-readable English message, safe to display in dev; UI localizes by `code`. */
  message: string;
  /** Structured extra data, e.g. `ValidationDetails`. */
  details: JsonObject | null;
}

/** Envelope kind (IPC_PROTOCOL.md §2). */
export const IpcKind = {
  /** Shell → Agent request; exactly one `IpcKind.Response` with the same id follows. */
  Request: 'request',
  /** Agent → Shell reply; copies the request id. */
  Response: 'response',
  /** Agent → Shell notification; fresh id, never answered. */
  Event: 'event',
} as const;
/** Envelope kind (IPC_PROTOCOL.md §2). */
export type IpcKind = (typeof IpcKind)[keyof typeof IpcKind];

/**
 * Every IPC message name (IPC_PROTOCOL.md §7–8). Requests are Shell → Agent; `Events` are Agent → Shell and are
 * re-emitted by the Shell as Tauri events `agent://<name>`.
 */
export const IpcNames = {
  /** `auth.*` */
  Auth: {
    /** Handshake; payload `AuthHelloRequest` → `AuthHelloResponse`. */
    Hello: 'auth.hello',
    /** `AuthLoginRequest` → `AuthLoginResponse`. */
    Login: 'auth.login',
    /** `AuthLogoutRequest` → `AuthLogoutResponse`. */
    Logout: 'auth.logout',
    /** — → `AuthStatusResponse`. */
    Status: 'auth.status',
    /** — → `QrLoginStart`. */
    QrStart: 'auth.qrStart',
  },
  /** `session.*` */
  Session: {
    /** — → `Session` or `null`. */
    Get: 'session.get',
    /** `SessionStartRequest` → `Session`. */
    Start: 'session.start',
    /** `SessionPauseRequest` → `Session`. */
    Pause: 'session.pause',
    /** — → `Session`. */
    Resume: 'session.resume',
    /** `SessionEndRequest` → `SessionEndResult`. */
    End: 'session.end',
    /** `SessionExtendRequest` → `Session`. */
    Extend: 'session.extend',
    /** `SessionLockRequest` → `Session`. */
    Lock: 'session.lock',
    /** `SessionUnlockRequest` → `Session`. */
    Unlock: 'session.unlock',
    /** — → `SessionTimeLeftResponse`. */
    TimeLeft: 'session.timeLeft',
  },
  /** `games.*` */
  Games: {
    /** `GamesListRequest` → `GamesListResponse`. */
    List: 'games.list',
    /** `GamesGetRequest` → `Game`. */
    Get: 'games.get',
    /** `GamesLaunchRequest` → `LaunchResult`. */
    Launch: 'games.launch',
    /** `GamesKillRequest` → `GamesKillResponse`. */
    Kill: 'games.kill',
    /** — → `GamesRunningResponse`. */
    Running: 'games.running',
    /** `GamesInstallStatusRequest` → `GameInstallStatus`. */
    InstallStatus: 'games.installStatus',
  },
  /** `apps.*` */
  Apps: {
    /** — → `AppsListResponse`. */
    List: 'apps.list',
    /** `AppsLaunchRequest` → `AppsLaunchResponse`. */
    Launch: 'apps.launch',
  },
  /** `wallet.*` */
  Wallet: {
    /** — → `Balance`. */
    Balance: 'wallet.balance',
    /** `WalletTariffsRequest` → `WalletTariffsResponse`. */
    Tariffs: 'wallet.tariffs',
    /** `WalletHistoryRequest` → `WalletHistoryResponse`. */
    History: 'wallet.history',
    /** `WalletTopupIntentRequest` → `TopupIntent`. */
    TopupIntent: 'wallet.topupIntent',
  },
  /** `shop.*` */
  Shop: {
    /** `ShopProductsRequest` → `ShopProductsResponse`. */
    Products: 'shop.products',
    /** `ShopOrderRequest` → `Order`. */
    Order: 'shop.order',
    /** `ShopOrderStatusRequest` → `Order`. */
    OrderStatus: 'shop.orderStatus',
    /** `ShopOrdersRequest` → `ShopOrdersResponse`. */
    Orders: 'shop.orders',
  },
  /** `chat.*` */
  Chat: {
    /** `ChatHistoryRequest` → `ChatHistoryResponse`. */
    History: 'chat.history',
    /** `ChatSendRequest` → `ChatMessage`. */
    Send: 'chat.send',
    /** `ChatMarkReadRequest` → `ChatMarkReadResponse`. */
    MarkRead: 'chat.markRead',
  },
  /** `booking.*` */
  Booking: {
    /** `BookingSeatsRequest` → `BookingSeatsResponse`. */
    Seats: 'booking.seats',
    /** `BookingReserveRequest` → `Booking`. */
    Reserve: 'booking.reserve',
    /** `BookingCancelRequest` → `Booking`. */
    Cancel: 'booking.cancel',
  },
  /** `tournaments.*` */
  Tournaments: {
    /** `TournamentsListRequest` → `TournamentsListResponse`. */
    List: 'tournaments.list',
    /** `TournamentsJoinRequest` → `Tournament`. */
    Join: 'tournaments.join',
    /** `TournamentsLeaderboardRequest` → `TournamentsLeaderboardResponse`. */
    Leaderboard: 'tournaments.leaderboard',
  },
  /** `profile.*` */
  Profile: {
    /** — → `User`. */
    Get: 'profile.get',
    /** `ProfileUpdateRequest` → `User`. */
    Update: 'profile.update',
    /** — → `UserStats`. */
    Stats: 'profile.stats',
    /** — → `ProfileAchievementsResponse`. */
    Achievements: 'profile.achievements',
    /** — → `Loyalty`. */
    Loyalty: 'profile.loyalty',
  },
  /** `settings.*` */
  Settings: {
    /** — → `ShellSettings`. */
    Get: 'settings.get',
    /** `SettingsSetRequest` → `ShellSettings`. */
    Set: 'settings.set',
  },
  /** `sys.*` */
  Sys: {
    /** `SysPingRequest` → response named `Sys.Pong` with `SysPongResponse`. */
    Ping: 'sys.ping',
    /** Response name of `Sys.Ping`. */
    Pong: 'sys.pong',
    /** — → `PcInfo`. */
    PcInfo: 'sys.pcInfo',
    /** `SysHardwareRequest` → `HardwareInfo`. */
    Hardware: 'sys.hardware',
    /** — → `PcMetrics` (last sample). */
    Metrics: 'sys.metrics',
    /** `SysCallAdminRequest` → `SysCallAdminResponse`. */
    CallAdmin: 'sys.callAdmin',
    /** `SysPowerRequest` → `ScheduledResult`. */
    Reboot: 'sys.reboot',
    /** `SysPowerRequest` → `ScheduledResult`. */
    Shutdown: 'sys.shutdown',
    /** `SysLockScreenRequest` → `OkResponse`. */
    LockScreen: 'sys.lockScreen',
    /** `SetVolumeRequest` → `VolumeState`. */
    SetVolume: 'sys.setVolume',
    /** `SysSetLocaleRequest` → `SysSetLocaleResponse`. */
    SetLocale: 'sys.setLocale',
    /** `SysUnlockAdminRequest` → `SysUnlockAdminResponse`. */
    UnlockAdmin: 'sys.unlockAdmin',
    /** `SysLogClientErrorRequest` → `OkResponse`. */
    LogClientError: 'sys.logClientError',
    /** `SysAckAdminMessageRequest` → `OkResponse`. */
    AckAdminMessage: 'sys.ackAdminMessage',
  },
  /** `policy.*` */
  Policy: {
    /** — → `Policy`. */
    Get: 'policy.get',
    /** `PolicyReloadRequest` → `PolicyReloadResponse`. */
    Reload: 'policy.reload',
  },
  /** `update.*` */
  Update: {
    /** — → `UpdateCheckResponse`. */
    Check: 'update.check',
    /** `UpdateApplyRequest` → `UpdateApplyResponse`. */
    Apply: 'update.apply',
  },
  /** Agent → Shell events (IPC_PROTOCOL.md §8). */
  Events: {
    /** Payload `Session`; any state/field change (≤ 1/s). */
    SessionUpdated: 'session.updated',
    /** Payload `SessionWarning`. */
    SessionWarning: 'session.warning',
    /** Payload `SessionEndedEvent`. */
    SessionEnded: 'session.ended',
    /** Payload `Balance`. */
    WalletUpdated: 'wallet.updated',
    /** Payload `ChatMessage`. */
    ChatMessage: 'chat.message',
    /** Payload `Notification`. */
    NotificationPush: 'notification.push',
    /** Payload `AdminMessage`. */
    AdminMessage: 'admin.message',
    /** Payload `RemoteControlEvent`. */
    AdminRemoteControl: 'admin.remoteControl',
    /** Payload `GameStateChanged`. */
    GameStateChanged: 'game.stateChanged',
    /** Payload `PolicyChanged`. */
    PolicyChanged: 'policy.changed',
    /** Payload `UpdateAvailable`. */
    UpdateAvailable: 'update.available',
    /** Payload `UpdateProgress`. */
    UpdateProgress: 'update.progress',
    /** Payload `UpdateReady`. */
    UpdateReady: 'update.ready',
    /** Payload `PcMetrics`. */
    SysMetrics: 'sys.metrics',
    /** Payload `ConnectivityEvent`. */
    SysConnectivity: 'sys.connectivity',
    /** Payload `ShellCommand`. */
    ShellCommand: 'shell.command',
    /** Payload `AuthExpired`. */
    AuthExpired: 'auth.expired',
    /** Payload `Order`. */
    ShopOrderUpdated: 'shop.orderUpdated',
  },
} as const;

/** `details` for `ErrorCode.GameLaunchFailed`. */
export interface LaunchFailedDetails {
  /** Launch stage, e.g. `lease`, `inject`, `createProcess`, `waitForWindow`. */
  stage: string;
  /** Launcher exit code when it exited. */
  exitCode?: number | null;
  /** Captured stderr tail, when any. */
  stderr?: string | null;
}

/** `details` for `ErrorCode.NotFound` when an IPC message name is unknown. */
export interface NameDetails {
  /** The unknown message name. */
  name: string;
}

/** Trivial `{ ok: true }` response. */
export interface OkResponse {
  /** Always `true`. */
  ok: boolean;
}

/** Standard page envelope `{ items, total, page, pageSize }` (SERVER_API.md §1). */
export interface PagedResult<T> {
  /** Items of this page. */
  items: T[];
  /** Total items across all pages. */
  total: number;
  /** 1-based page number. */
  page: number;
  /** Page size. */
  pageSize: number;
}

/** `details` for `ErrorCode.PolicyDenied`. */
export interface PolicyDeniedDetails {
  /** Policy rule identifier, e.g. `ageRating`, `alreadyRunning`, `postpaidNotAllowed`. */
  rule: string;
  /** Optional settings field locked by policy (`settings.set`). */
  field?: string | null;
}

/** Request of `policy.reload`. */
export interface PolicyReloadRequest {
  /** Bypass the ETag cache. */
  force?: boolean | null;
}

/** Where the policy returned by `policy.reload` came from. */
export const PolicySource = {
  /** Fetched from the server. */
  Server: 'server',
  /** Loaded from `cache\policies.json`. */
  Cache: 'cache',
  /** Loaded from `policies.json` (last applied snapshot). */
  File: 'file',
} as const;
/** Where the policy returned by `policy.reload` came from. */
export type PolicySource = (typeof PolicySource)[keyof typeof PolicySource];

/** Response of `profile.achievements` and `GET /users/{userId}/achievements`. */
export interface ProfileAchievementsResponse {
  /** Achievements. */
  items: Achievement[];
}

/** `details` for `ErrorCode.RateLimited`. */
export interface RateLimitDetails {
  /** Seconds the caller should wait before retrying. */
  retryAfterSec: number;
}

/**
 * `details` carrying a single `reason` code (`ErrorCode.Unauthorized`, `ErrorCode.Forbidden`, `ErrorCode.Conflict`).
 */
export interface ReasonDetails {
  /** Reason code, e.g. `expired`, `banned`, `outOfStock`, `pendingApproval`. */
  reason: string;
}

/** Request of `session.end`. */
export interface SessionEndRequest {
  /** End reason; defaults to `SessionEndReason.User`. */
  reason?: SessionEndReason | null;
}

/** Request of `session.extend` and body of `POST /sessions/{id}/extend`. */
export interface SessionExtendRequest {
  /** Minutes to add. */
  minutes: number;
  /** Tariff to bill; defaults to the current one. */
  tariffId?: string | null;
}

/** Request of `session.lock`. */
export interface SessionLockRequest {
  /** Free-text reason. */
  reason?: string | null;
}

/** Request of `session.pause`. */
export interface SessionPauseRequest {
  /** Free-text reason. */
  reason?: string | null;
}

/** Request of `session.start`. */
export interface SessionStartRequest {
  /** Tariff. */
  tariffId: string;
  /** `true` = charge now for `minutes`; `false` = postpaid open-ended. */
  prepaid: boolean;
  /** Minutes to buy; required unless the tariff is a package; within `minMinutes..maxMinutes`. */
  minutes?: number | null;
}

/** Response of `session.timeLeft`; used for drift correction every 30 s. Never errors when idle. */
export interface SessionTimeLeftResponse {
  /** Session state (`SessionState.Idle` when none). */
  state: SessionState;
  /** Seconds remaining (−1 open-ended, 0 when idle). */
  secondsLeft: number;
  /** Seconds used. */
  secondsUsed: number;
  /** Agent's estimate of server time. */
  serverTime: string;
  /** Session id, when any. */
  sessionId?: string | null;
  /** Scheduled end, when any. */
  endsAt?: string | null;
}

/** Request of `session.unlock`; exactly one of the secrets is given. */
export interface SessionUnlockRequest {
  /** Account password. */
  password?: string | null;
  /** 4–6 digit user PIN. */
  pin?: string | null;
}

/** Request of `sys.setVolume` and payload of the `setVolume` server command. */
export interface SetVolumeRequest {
  /** Volume 0–100. */
  level: number;
  /** Mute state; unchanged when `null`. */
  muted?: boolean | null;
}

/** Request of `settings.set`; partial, at least one key. */
export interface SettingsSetRequest {
  /** UI locale. */
  locale?: Locale | null;
  /** Theme id (must exist). */
  theme?: string | null;
  /** Volume 0–100. */
  volume?: number | null;
  /** Muted. */
  muted?: boolean | null;
  /** Idle lock timeout. */
  idleTimeoutSec?: number | null;
  /** Show the metrics overlay. */
  showMetricsOverlay?: boolean | null;
  /** Allow the on-screen keyboard. */
  allowVirtualKeyboard?: boolean | null;
  /** UI sounds. */
  uiSounds?: boolean | null;
}

/** Shell capabilities advertised in `AuthHelloRequest.Capabilities`. */
export const ShellCapabilities = {
  /** Gamepad navigation. */
  Gamepad: 'gamepad',
  /** On-screen keyboard. */
  VirtualKeyboard: 'virtualKeyboard',
  /** Multi-monitor handling. */
  MultiMonitor: 'multiMonitor',
  /** Overlay window. */
  Overlay: 'overlay',
} as const;
/** One of the {@link ShellCapabilities} values. */
export type ShellCapability = (typeof ShellCapabilities)[keyof typeof ShellCapabilities];

/** Feature toggles exposed to the UI (`shell.json → features`). */
export interface ShellFeatures {
  /** Shop. */
  shop: boolean;
  /** Chat. */
  chat: boolean;
  /** Booking. */
  booking: boolean;
  /** Tournaments. */
  tournaments: boolean;
  /** Profile. */
  profile: boolean;
  /** Top-up. */
  topup: boolean;
  /** Apps. */
  apps: boolean;
  /** Call admin. */
  callAdmin: boolean;
}

/** Settings subset of `shell.json` exposed to the UI (IPC_PROTOCOL.md §6.21); persisted by the Agent. */
export interface ShellSettings {
  /** UI locale. */
  locale: Locale;
  /** Theme id. */
  theme: string;
  /** Installed themes (read-only). */
  availableThemes: string[];
  /** Volume 0–100. */
  volume: number;
  /** Muted. */
  muted: boolean;
  /** Idle lock timeout. */
  idleTimeoutSec: number;
  /** Show the metrics overlay. */
  showMetricsOverlay: boolean;
  /** Allow the on-screen keyboard. */
  allowVirtualKeyboard: boolean;
  /** UI sounds. */
  uiSounds: boolean;
  /** Feature toggles (read-only). */
  features: ShellFeatures;
}

/** Request of `shop.order`. */
export interface ShopOrderRequest {
  /** Lines (1–20, qty 1–99). */
  items: OrderLineRequest[];
  /** Client-generated key forwarded as `Idempotency-Key`. */
  idempotencyKey: string;
  /** Note for staff. */
  note?: string | null;
}

/** Request of `shop.orderStatus`. */
export interface ShopOrderStatusRequest {
  /** Order id. */
  orderId: string;
}

/** Request of `shop.orders`. */
export interface ShopOrdersRequest {
  /** 1-based page. */
  page?: number | null;
  /** Page size. */
  pageSize?: number | null;
  /** Only orders still in progress. */
  activeOnly?: boolean | null;
}

/** Response of `shop.orders`. */
export interface ShopOrdersResponse {
  /** Orders. */
  items: Order[];
  /** Total orders. */
  total: number;
}

/** Request of `shop.products`. */
export interface ShopProductsRequest {
  /** Filter by category. */
  category?: ProductCategory | null;
  /** Free-text search. */
  search?: string | null;
}

/** Response of `shop.products` and `GET /shop/products`. */
export interface ShopProductsResponse {
  /** Products. */
  items: Product[];
}

/** Request of `sys.ackAdminMessage`. */
export interface SysAckAdminMessageRequest {
  /** Id of the acknowledged `AdminMessage`. */
  id: string;
}

/** Request of `sys.callAdmin` (rate limited 1 per 30 s). */
export interface SysCallAdminRequest {
  /** Category. */
  category: CallAdminCategory;
  /** Free text. */
  message?: string | null;
}

/**
 * Response of `sys.callAdmin` and `POST /support/call-admin`. Offline: client-generated ticket id,
 * `queuePosition``null`.
 */
export interface SysCallAdminResponse {
  /** Ticket id. */
  ticketId: string;
  /** Creation time. */
  createdAt: string;
  /** Position in the admin queue, when known. */
  queuePosition?: number | null;
}

/** Request of `sys.hardware`. */
export interface SysHardwareRequest {
  /** Force a rescan instead of the cached inventory. */
  refresh?: boolean | null;
}

/** Request of `sys.lockScreen`. */
export interface SysLockScreenRequest {
  /** Free-text reason. */
  reason?: string | null;
}

/** Request of `sys.logClientError` (rate limited 10/s, silently dropped beyond). */
export interface SysLogClientErrorRequest {
  /** Severity. */
  level: ClientErrorLevel;
  /** Message. */
  message: string;
  /** Stack trace. */
  stack?: string | null;
  /** Frontend route. */
  route?: string | null;
}

/** Request of `sys.ping`. */
export interface SysPingRequest {
  /** Monotonic sequence number. */
  seq: number;
  /** Shell send time. */
  sentAt: string;
}

/** Response (`sys.pong`) to `sys.ping`. */
export interface SysPongResponse {
  /** Echoed sequence number. */
  seq: number;
  /** Echoed send time. */
  sentAt: string;
  /** Agent receive time. */
  receivedAt: string;
  /** Server connectivity. */
  connectivity: ConnectivityState;
}

/** Request of `sys.reboot` / `sys.shutdown`. */
export interface SysPowerRequest {
  /** Delay before the action. */
  delaySec?: number | null;
  /** Free-text reason. */
  reason?: string | null;
}

/** Request of `sys.setLocale`. */
export interface SysSetLocaleRequest {
  /** New locale. */
  locale: Locale;
}

/** Response of `sys.setLocale`. */
export interface SysSetLocaleResponse {
  /** Applied locale. */
  locale: Locale;
}

/** Request of `sys.unlockAdmin` (rate limited 3 attempts/min). */
export interface SysUnlockAdminRequest {
  /** Admin PIN. */
  pin: string;
}

/** Response of `sys.unlockAdmin`; grants the kiosk exit path for 5 minutes. */
export interface SysUnlockAdminResponse {
  /** Always `true`. */
  ok: boolean;
  /** Short-lived token passed to `kiosk_exit`. */
  adminToken: string;
  /** Token expiry. */
  expiresAt: string;
}

/** Response of `GET /tariffs`. */
export interface TariffsResponse {
  /** Tariffs. */
  items: Tariff[];
  /** Server time. */
  serverTime: string;
}

/** Request of `tournaments.join`. */
export interface TournamentsJoinRequest {
  /** Tournament id. */
  tournamentId: string;
}

/** Request of `tournaments.leaderboard`. */
export interface TournamentsLeaderboardRequest {
  /** Tournament id. */
  tournamentId: string;
  /** Max entries (≤ 100). */
  limit?: number | null;
}

/** Response of `tournaments.leaderboard` and `GET /tournaments/{id}/leaderboard`. */
export interface TournamentsLeaderboardResponse {
  /** Tournament id. */
  tournamentId: string;
  /** Top entries. */
  entries: LeaderboardEntry[];
  /** Last update. */
  updatedAt: string;
  /** Current user's entry when outside the top list. */
  me?: LeaderboardEntry | null;
}

/** Request of `tournaments.list`. */
export interface TournamentsListRequest {
  /** Filter by state. */
  state?: TournamentState | null;
  /** Filter by game. */
  gameId?: string | null;
}

/** Response of `tournaments.list` and `GET /tournaments`. */
export interface TournamentsListResponse {
  /** Tournaments. */
  items: Tournament[];
}

/** `details` for `ErrorCode.Internal` (and any server error mapped to IPC). */
export interface TraceDetails {
  /** Trace id to correlate logs. */
  traceId: string;
}

/** Response of `update.apply` and result of the `update` server command. */
export interface UpdateApplyResponse {
  /** Whether the apply was scheduled. */
  scheduled: boolean;
  /** When it will run. */
  at?: string | null;
}

/** `details` for `ErrorCode.Validation`. */
export interface ValidationDetails {
  /** JSON path of the offending field, e.g. `minutes` or `items[2].qty`. */
  field: string;
  /** Machine-readable reason code, e.g. `required`, `min`, `max`, `format`. */
  reason: string;
}

/** `details` for `ErrorCode.VersionMismatch`. */
export interface VersionMismatchDetails {
  /** Supported protocol majors. */
  supported: number[];
  /** Version received. */
  got: number;
}

/** Response of `sys.setVolume` and result of the `setVolume` server command. */
export interface VolumeState {
  /** Applied volume. */
  level: number;
  /** Applied mute state. */
  muted: boolean;
}

/** Request of `wallet.history` (and query of `GET /wallet/{userId}/transactions`). */
export interface WalletHistoryRequest {
  /** 1-based page. */
  page?: number | null;
  /** Page size. */
  pageSize?: number | null;
  /** Inclusive lower bound. */
  from?: string | null;
  /** Exclusive upper bound. */
  to?: string | null;
  /** Filter by type. */
  type?: TransactionType | null;
}

/** Request of `wallet.tariffs`. */
export interface WalletTariffsRequest {
  /** Zone; defaults to this PC's zone. */
  zone?: string | null;
}

/** Response of `wallet.tariffs` (cached offline). */
export interface WalletTariffsResponse {
  /** Tariffs. */
  items: Tariff[];
  /** Zone the list applies to. */
  zone: string;
  /** Server time for window evaluation. */
  serverTime: string;
}

/** Request of `wallet.topupIntent`. */
export interface WalletTopupIntentRequest {
  /** Amount ≥ 1 000 UZS; `TopupProvider.Cash` creates an admin ticket. */
  amount: Money;
  /** Provider. */
  provider: TopupProvider;
}

/**
 * Every Shell → Agent IPC request (IPC_PROTOCOL.md §7). Wire form is the IPC name (`auth.hello`, …) via
 * `AgentCommandJsonConverter`; use `AgentCommands.ToIpcName` / `AgentCommands.TryParse`.
 */
export const AgentCommand = {
  /** `auth.hello` */
  AuthHello: 'auth.hello',
  /** `auth.login` */
  AuthLogin: 'auth.login',
  /** `auth.logout` */
  AuthLogout: 'auth.logout',
  /** `auth.status` */
  AuthStatus: 'auth.status',
  /** `auth.qrStart` */
  AuthQrStart: 'auth.qrStart',
  /** `session.get` */
  SessionGet: 'session.get',
  /** `session.start` */
  SessionStart: 'session.start',
  /** `session.pause` */
  SessionPause: 'session.pause',
  /** `session.resume` */
  SessionResume: 'session.resume',
  /** `session.end` */
  SessionEnd: 'session.end',
  /** `session.extend` */
  SessionExtend: 'session.extend',
  /** `session.lock` */
  SessionLock: 'session.lock',
  /** `session.unlock` */
  SessionUnlock: 'session.unlock',
  /** `session.timeLeft` */
  SessionTimeLeft: 'session.timeLeft',
  /** `games.list` */
  GamesList: 'games.list',
  /** `games.get` */
  GamesGet: 'games.get',
  /** `games.launch` */
  GamesLaunch: 'games.launch',
  /** `games.kill` */
  GamesKill: 'games.kill',
  /** `games.running` */
  GamesRunning: 'games.running',
  /** `games.installStatus` */
  GamesInstallStatus: 'games.installStatus',
  /** `apps.list` */
  AppsList: 'apps.list',
  /** `apps.launch` */
  AppsLaunch: 'apps.launch',
  /** `wallet.balance` */
  WalletBalance: 'wallet.balance',
  /** `wallet.tariffs` */
  WalletTariffs: 'wallet.tariffs',
  /** `wallet.history` */
  WalletHistory: 'wallet.history',
  /** `wallet.topupIntent` */
  WalletTopupIntent: 'wallet.topupIntent',
  /** `shop.products` */
  ShopProducts: 'shop.products',
  /** `shop.order` */
  ShopOrder: 'shop.order',
  /** `shop.orderStatus` */
  ShopOrderStatus: 'shop.orderStatus',
  /** `shop.orders` */
  ShopOrders: 'shop.orders',
  /** `chat.history` */
  ChatHistory: 'chat.history',
  /** `chat.send` */
  ChatSend: 'chat.send',
  /** `chat.markRead` */
  ChatMarkRead: 'chat.markRead',
  /** `booking.seats` */
  BookingSeats: 'booking.seats',
  /** `booking.reserve` */
  BookingReserve: 'booking.reserve',
  /** `booking.cancel` */
  BookingCancel: 'booking.cancel',
  /** `tournaments.list` */
  TournamentsList: 'tournaments.list',
  /** `tournaments.join` */
  TournamentsJoin: 'tournaments.join',
  /** `tournaments.leaderboard` */
  TournamentsLeaderboard: 'tournaments.leaderboard',
  /** `profile.get` */
  ProfileGet: 'profile.get',
  /** `profile.update` */
  ProfileUpdate: 'profile.update',
  /** `profile.stats` */
  ProfileStats: 'profile.stats',
  /** `profile.achievements` */
  ProfileAchievements: 'profile.achievements',
  /** `profile.loyalty` */
  ProfileLoyalty: 'profile.loyalty',
  /** `settings.get` */
  SettingsGet: 'settings.get',
  /** `settings.set` */
  SettingsSet: 'settings.set',
  /** `sys.ping` (answered as `sys.pong`) */
  SysPing: 'sys.ping',
  /** `sys.pcInfo` */
  SysPcInfo: 'sys.pcInfo',
  /** `sys.hardware` */
  SysHardware: 'sys.hardware',
  /** `sys.metrics` */
  SysMetrics: 'sys.metrics',
  /** `sys.callAdmin` */
  SysCallAdmin: 'sys.callAdmin',
  /** `sys.reboot` */
  SysReboot: 'sys.reboot',
  /** `sys.shutdown` */
  SysShutdown: 'sys.shutdown',
  /** `sys.lockScreen` */
  SysLockScreen: 'sys.lockScreen',
  /** `sys.setVolume` */
  SysSetVolume: 'sys.setVolume',
  /** `sys.setLocale` */
  SysSetLocale: 'sys.setLocale',
  /** `sys.unlockAdmin` */
  SysUnlockAdmin: 'sys.unlockAdmin',
  /** `sys.logClientError` */
  SysLogClientError: 'sys.logClientError',
  /** `sys.ackAdminMessage` */
  SysAckAdminMessage: 'sys.ackAdminMessage',
  /** `policy.get` */
  PolicyGet: 'policy.get',
  /** `policy.reload` */
  PolicyReload: 'policy.reload',
  /** `update.check` */
  UpdateCheck: 'update.check',
  /** `update.apply` */
  UpdateApply: 'update.apply',
} as const;
/**
 * Every Shell → Agent IPC request (IPC_PROTOCOL.md §7). Wire form is the IPC name (`auth.hello`, …) via
 * `AgentCommandJsonConverter`; use `AgentCommands.ToIpcName` / `AgentCommands.TryParse`.
 */
export type AgentCommand = (typeof AgentCommand)[keyof typeof AgentCommand];

/** Events the Agent emits over WS (SERVER_API.md §6.2); replayed via REST when offline. */
export const AgentEventType = {
  /** Payload `SessionStartedEvent`. */
  SessionStarted: 'sessionStarted',
  /** Payload `SessionEndedEvent`. */
  SessionEnded: 'sessionEnded',
  /** Payload `GameLaunchedEvent`. */
  GameLaunched: 'gameLaunched',
  /** Payload `GameExitedEvent`. */
  GameExited: 'gameExited',
  /** Payload `AntiCheatReport`. */
  AnticheatViolation: 'anticheatViolation',
  /** Payload `HardwareChangedEvent`. */
  HardwareChanged: 'hardwareChanged',
  /** Payload `OfflineQueueFlushedEvent`. */
  OfflineQueueFlushed: 'offlineQueueFlushed',
} as const;
/** Events the Agent emits over WS (SERVER_API.md §6.2); replayed via REST when offline. */
export type AgentEventType = (typeof AgentEventType)[keyof typeof AgentEventType];

/** Body of `POST /agents/refresh`. */
export interface AgentRefreshRequest {
  /** Current refresh token. */
  refreshToken: string;
  /** Hardware id. */
  hwid: string;
}

/** Response of `POST /agents/refresh`. */
export interface AgentRefreshResponse {
  /** New JWT. */
  accessToken: string;
  /** New refresh token (old one is invalid). */
  refreshToken: string;
  /** Access token expiry. */
  expiresAt: string;
  /** Present only when rotated; must be switched atomically. */
  signingSecret?: string | null;
}

/** Body of `POST /agents/register` (auth `X-Club-Key`). */
export interface AgentRegisterRequest {
  /** Hardware id (sha256 hex). */
  hwid: string;
  /** Windows machine name. */
  machineName: string;
  /** Agent semver. */
  agentVersion: string;
  /** Inventory. */
  hardware: HardwareInfo;
  /** IPv4 address. */
  ipAddress: string;
  /** Primary MAC. */
  macAddress: string;
  /** Hint for re-registration after reinstall. */
  previousPcId?: string | null;
}

/** Response of `POST /agents/register`. Secrets are stored DPAPI-protected in `secure\agent.tokens`. */
export interface AgentRegisterResponse {
  /** Assigned PC id. */
  pcId: string;
  /** PC record. */
  pc: Pc;
  /** Agent JWT (≈ 1 h). */
  accessToken: string;
  /** Opaque refresh token (30 d, single-use rotation). */
  refreshToken: string;
  /** Base64 32-byte HMAC key for request signing. */
  signingSecret: string;
  /** Access token expiry. */
  expiresAt: string;
  /** Server clock. */
  serverTime: string;
  /** Server configuration overrides. */
  config: AgentServerConfig;
}

/** Body of `POST /support/call-admin`. Sent with an `Idempotency-Key`. */
export interface CallAdminTicketRequest {
  /** PC. */
  pcId: string;
  /** Logged-in user, when any. */
  userId?: string | null;
  /** Category. */
  category: CallAdminCategory;
  /** Free text. */
  message?: string | null;
  /** Request time (client clock, for offline replay). */
  at: string;
}

/** Payload of `ServerCommandType.EndSession`. */
export interface EndSessionCommand {
  /** Session to end. */
  sessionId: string;
  /** End reason. */
  reason: SessionEndReason;
}

/** Payload of `ServerCommandType.ExtendSession`. */
export interface ExtendSessionCommand {
  /** Session to extend. */
  sessionId: string;
  /** Minutes to add. */
  minutes: number;
  /** Charge the wallet (`false` when already billed server-side). */
  charge: boolean;
}

/** Payload of `AgentEventType.GameExited`. */
export interface GameExitedEvent {
  /** Session. */
  sessionId: string;
  /** Game. */
  gameId: string;
  /** Process id. */
  pid: number;
  /** Exit code. */
  exitCode: number;
  /** Seconds played. */
  playedSec: number;
  /** Exit time. */
  at: string;
}

/** Payload of `AgentEventType.GameLaunched`. */
export interface GameLaunchedEvent {
  /** Session. */
  sessionId: string;
  /** Game. */
  gameId: string;
  /** Process id. */
  pid: number;
  /** Lease used, when any. */
  accountLeaseId?: string | null;
  /** Launch time. */
  at: string;
}

/** Payload of `AgentEventType.HardwareChanged`. */
export interface HardwareChangedEvent {
  /** New inventory. */
  hardware: HardwareInfo;
  /** Changed top-level keys (`gpu`, `disks`, …). */
  diff: string[];
}

/** Response of `POST /agents/{pcId}/heartbeat`. */
export interface HeartbeatResponse {
  /** Server clock (used for offset correction). */
  serverTime: string;
  /** Authoritative status. */
  pcStatus: PcStatus;
  /** Latest policy version; reload when newer than applied. */
  policyVersion: number;
  /** Latest config version. */
  configVersion: number;
  /** Games/apps catalogue version; refresh lists when changed. */
  catalogVersion: string;
  /** Commands queued while WS was down. */
  pendingCommands: number;
  /** Server view of the current session for reconciliation. */
  session?: Session | null;
}

/** Running game summary in a heartbeat. */
export interface HeartbeatRunningGame {
  /** Game. */
  gameId: string;
  /** Process id. */
  pid: number;
  /** Launch time. */
  startedAt: string;
}

/** Body of `POST /agents/{pcId}/heartbeat` (every `session.heartbeatSec`). */
export interface HeartbeatRequest {
  /** Agent's own view of the PC status. */
  status: PcStatus;
  /** Open session, when any. */
  currentSessionId?: string | null;
  /** Agent semver. */
  agentVersion: string;
  /** Shell semver. */
  shellVersion: string;
  /** OS uptime. */
  uptimeSec: number;
  /** IPv4 address. */
  ipAddress: string;
  /** Applied policy version. */
  policyVersion: number;
  /** Running games. */
  runningGames: HeartbeatRunningGame[];
  /** Outbox size. */
  offlineQueue: number;
  /** Whether the Shell pipe connection is alive. */
  shellConnected: boolean;
}

/** Authentication level an IPC request requires (IPC_PROTOCOL.md §7 "auth" column). */
export const IpcAuthLevel = {
  /** No handshake required (`auth.hello`, `sys.ping`). */
  None: 'none',
  /** Successful `auth.hello` on the connection. */
  Hello: 'hello',
  /** A logged-in user. */
  User: 'user',
  /** An active or paused session. */
  Session: 'session',
} as const;
/** Authentication level an IPC request requires (IPC_PROTOCOL.md §7 "auth" column). */
export type IpcAuthLevel = (typeof IpcAuthLevel)[keyof typeof IpcAuthLevel];

/** Payload of `ServerCommandType.KillGame`. */
export interface KillGameCommand {
  /** Game to kill. */
  gameId?: string | null;
  /** Process to kill. */
  pid?: number | null;
  /** Terminate immediately instead of a graceful close. */
  force: boolean;
}

/** Payload of `ServerCommandType.Lock`; also `shell.command{lock}` args. */
export interface LockCommand {
  /** Machine-readable reason. */
  reason?: string | null;
  /** Message to display. */
  message?: string | null;
}

/** Payload of `ServerCommandType.Message`. */
export interface MessageCommand {
  /** Message id (acked via `sys.ackAdminMessage`). */
  id: string;
  /** Sender name. */
  from: string;
  /** Text. */
  text: string;
  /** Severity. */
  level: NotificationLevel;
  /** User must acknowledge. */
  requiresAck: boolean;
}

/** Result of `ServerCommandType.Message`; a second ack is sent when the user acknowledges. */
export interface MessageDeliveryResult {
  /** When the Shell displayed it. */
  deliveredAt: string;
  /** When the user acknowledged it. */
  ackedAt?: string | null;
}

/** Payload of `AgentEventType.OfflineQueueFlushed`. */
export interface OfflineQueueFlushedEvent {
  /** Entries delivered. */
  count: number;
  /** Entries moved to the dead-letter table. */
  deadlettered: number;
  /** Start of the offline period. */
  offlineFrom: string;
  /** End of the offline period. */
  offlineTo: string;
}

/** Payload of `WsPushKind.PcStatusChanged`. */
export interface PcStatusChangedPush {
  /** PC. */
  pcId: string;
  /** New status. */
  status: PcStatus;
}

/** Payload of `ServerCommandType.Reboot` and `ServerCommandType.Shutdown`. */
export interface PowerCommand {
  /** Delay before the action. */
  delaySec: number;
  /** End an active session first. */
  force: boolean;
  /** Message to display. */
  message?: string | null;
}

/** Payload of `ServerCommandType.RefreshConfig`; all flags `false`/absent = refresh everything. */
export interface RefreshConfigCommand {
  /** Re-fetch `/agents/{pcId}/config`. */
  config?: boolean | null;
  /** Re-fetch games. */
  games?: boolean | null;
  /** Re-fetch apps. */
  apps?: boolean | null;
  /** Re-fetch tariffs. */
  tariffs?: boolean | null;
  /** Re-fetch shop products. */
  products?: boolean | null;
  /** Re-download themes. */
  themes?: boolean | null;
}

/** Result of `ServerCommandType.RefreshConfig`. */
export interface RefreshConfigResult {
  /** Caches refreshed (`config`, `games`, `apps`, `tariffs`, `products`, `themes`). */
  refreshed: string[];
}

/** Result of `ServerCommandType.ReloadPolicy`. */
export interface ReloadPolicyResult {
  /** Policy version now in effect. */
  version: number;
}

/** Payload of `ServerCommandType.RemoteControlStart`. */
export interface RemoteControlStartCommand {
  /** Relay session token. */
  sessionToken: string;
  /** Relay `wss://` URL. */
  relayUrl: string;
  /** Capture frame rate. */
  fps: number;
  /** Allow remote keyboard/mouse input. */
  allowInput: boolean;
  /** Admin shown in the on-screen indicator. */
  adminName: string;
}

/** Result of `ServerCommandType.RemoteControlStart`. */
export interface RemoteControlStartResult {
  /** Start time. */
  startedAt: string;
}

/** Payload of `ServerCommandType.RemoteControlStop`. */
export interface RemoteControlStopCommand {
  /** Relay session token. */
  sessionToken: string;
}

/** Result of `ServerCommandType.RemoteControlStop`. */
export interface RemoteControlStopResult {
  /** Stop time. */
  stoppedAt: string;
  /** Session length. */
  durationSec: number;
}

/** Result of power commands and `sys.reboot`/`sys.shutdown`. */
export interface ScheduledResult {
  /** When the action will run. */
  scheduledAt: string;
}

/** Payload of `ServerCommandType.Screenshot`. */
export interface ScreenshotCommand {
  /** JPEG quality 1–100. */
  quality: number;
  /** Pre-signed `PUT` URL for the JPEG. */
  uploadUrl: string;
  /** Monitor index; `null` = primary. */
  monitor?: number | null;
  /** Downscale to this width. */
  maxWidth?: number | null;
}

/** Result of `ServerCommandType.Screenshot`. */
export interface ScreenshotResult {
  /** Image width. */
  width: number;
  /** Image height. */
  height: number;
  /** Uploaded size. */
  bytes: number;
  /** Upload time. */
  uploadedAt: string;
}

/** Command types the server may send over WS / `GET /agents/{pcId}/commands` (SERVER_API.md §6.1). */
export const ServerCommandType = {
  /** Lock the session / show idle lock; payload `LockCommand`; result `null`. */
  Lock: 'lock',
  /** Unlock; no payload; result `null`. */
  Unlock: 'unlock',
  /** Show an admin message; payload `MessageCommand`; result `MessageDeliveryResult`. */
  Message: 'message',
  /** Reboot; payload `PowerCommand`; result `ScheduledResult`. */
  Reboot: 'reboot',
  /** Shut down; payload `PowerCommand`; result `ScheduledResult`. */
  Shutdown: 'shutdown',
  /** Send a Wake-on-LAN packet to another PC; payload `WakeCommand`; result `null`. */
  Wake: 'wake',
  /** End the session; payload `EndSessionCommand`; result `SessionResult`. */
  EndSession: 'endSession',
  /** Extend the session; payload `ExtendSessionCommand`; result `SessionResult`. */
  ExtendSession: 'extendSession',
  /** Launch a game; payload `LaunchRequest`; result `LaunchResult`. */
  LaunchGame: 'launchGame',
  /** Kill a game; payload `KillGameCommand`; result `GamesKillResponse`. */
  KillGame: 'killGame',
  /** Apply a policy; payload `Policy`; result `SetPolicyResult`. */
  SetPolicy: 'setPolicy',
  /** Re-fetch and apply the policy; no payload; result `ReloadPolicyResult`. */
  ReloadPolicy: 'reloadPolicy',
  /** Capture the screen; payload `ScreenshotCommand`; result `ScreenshotResult`. */
  Screenshot: 'screenshot',
  /** Start remote control; payload `RemoteControlStartCommand`; result `RemoteControlStartResult`. */
  RemoteControlStart: 'remoteControlStart',
  /** Stop remote control; payload `RemoteControlStopCommand`; result `RemoteControlStopResult`. */
  RemoteControlStop: 'remoteControlStop',
  /** Check/apply an update; payload `UpdateCommand`; result `UpdateApplyResponse`. */
  Update: 'update',
  /** Show ads; payload `ShowAdsArgs`; result `null`. */
  ShowAds: 'showAds',
  /** Set volume; payload `SetVolumeRequest`; result `VolumeState`. */
  SetVolume: 'setVolume',
  /** Re-fetch caches; payload `RefreshConfigCommand`; result `RefreshConfigResult`. */
  RefreshConfig: 'refreshConfig',
} as const;
/** Command types the server may send over WS / `GET /agents/{pcId}/commands` (SERVER_API.md §6.1). */
export type ServerCommandType = (typeof ServerCommandType)[keyof typeof ServerCommandType];

/** Response of `GET /agents/{pcId}/commands`. */
export interface ServerCommandsResponse {
  /** Pending commands, oldest first. */
  items: ServerCommandEnvelope[];
}

/** Result carrying the resulting session. */
export interface SessionResult {
  /** Session after the command. */
  session: Session;
}

/** Result of `ServerCommandType.SetPolicy`. */
export interface SetPolicyResult {
  /** Policy version. */
  version: number;
  /** Whether it was applied without errors. */
  applied: boolean;
}

/** Agent diagnostic event in a telemetry batch. */
export interface TelemetryEvent {
  /** Kind (`TelemetryEventKinds`). */
  kind: string;
  /** Event time. */
  at: string;
  /** Structured data. */
  data: JsonObject;
}

/** Body of `POST /agents/{pcId}/telemetry`. */
export interface TelemetryBatch {
  /** Metric samples (≤ 120). */
  samples: PcMetrics[];
  /** Diagnostic events. */
  events: TelemetryEvent[];
  /** Inventory when changed / on rescan. */
  hardware?: HardwareInfo | null;
  /** Last ≤ 50 Warning+ log lines when `events` is non-empty. */
  logsTail?: string[] | null;
}
/** Maximum samples per batch. */
export const TELEMETRY_MAX_SAMPLES = 120;
/** Maximum log lines per batch. */
export const TELEMETRY_MAX_LOG_LINES = 50;

/** Well-known values of `TelemetryEvent.Kind`. */
export const TelemetryEventKinds = {
  /** Shell process crashed. */
  ShellCrash: 'shellCrash',
  /** Shell restart limit exceeded. */
  ShellCrashLoop: 'shellCrashLoop',
  /** Policy could not be applied. */
  PolicyApplyFailed: 'policyApplyFailed',
  /** Update failed. */
  UpdateFailed: 'updateFailed',
  /** Named-pipe error. */
  PipeError: 'pipeError',
  /** Launcher error. */
  LauncherError: 'launcherError',
  /** Outbox entry dead-lettered. */
  Deadletter: 'deadletter',
} as const;
/** One of the {@link TelemetryEventKinds} values. */
export type TelemetryEventKind = (typeof TelemetryEventKinds)[keyof typeof TelemetryEventKinds];

/** Update channel. */
export const UpdateChannel = {
  /** Stable releases. */
  Stable: 'stable',
  /** Beta releases. */
  Beta: 'beta',
} as const;
/** Update channel. */
export type UpdateChannel = (typeof UpdateChannel)[keyof typeof UpdateChannel];

/** Updatable component. */
export const UpdateComponent = {
  /** ClubShellAgent service. */
  Agent: 'agent',
  /** Kiosk shell. */
  Shell: 'shell',
} as const;
/** Updatable component. */
export type UpdateComponent = (typeof UpdateComponent)[keyof typeof UpdateComponent];

/** Request of `update.apply`. */
export interface UpdateApplyRequest {
  /** Component whose staged package to apply. */
  component: UpdateComponent;
}

/** Update package descriptor (IPC_PROTOCOL.md §6.19; `GET /updates/{channel}/manifest`). */
export interface UpdateManifest {
  /** Channel. */
  channel: UpdateChannel;
  /** Component. */
  component: UpdateComponent;
  /** Package semver. */
  version: string;
  /** HTTPS download URL (Bearer required, `Range` supported). */
  url: string;
  /** Lower-case hex SHA-256 of the package. */
  sha256: string;
  /** Package size in bytes. */
  size: number;
  /** Base64 RSA-PSS-SHA256 signature over the raw package bytes. */
  signature: string;
  /** Markdown release notes. */
  releaseNotes: string;
  /** Must be applied even during a session (after a 60 s notice). */
  mandatory: boolean;
  /** Publication time. */
  publishedAt: string;
  /** Minimum Agent version required (shell packages). */
  minAgentVersion?: string | null;
}

/** Response of `update.check`. */
export interface UpdateCheckResponse {
  /** Installed versions. */
  current: ComponentVersions;
  /** Available Agent update, when any. */
  agent?: UpdateManifest | null;
  /** Available Shell update, when any. */
  shell?: UpdateManifest | null;
}

/** Payload of `ServerCommandType.Update`. */
export interface UpdateCommand {
  /** Component to update. */
  component: UpdateComponent;
  /** Apply immediately (subject to session/mandatory rules). */
  applyNow: boolean;
  /** Manifest to use; `null` = fetch. */
  manifest?: UpdateManifest | null;
}

/** Phase reported by `update.progress`. */
export const UpdatePhase = {
  /** Downloading the package. */
  Downloading: 'downloading',
  /** Verifying SHA-256 and signature. */
  Verifying: 'verifying',
  /** Copying to `pending-update\`. */
  Staging: 'staging',
  /** Installing. */
  Applying: 'applying',
  /** Failed; `error` set. */
  Failed: 'failed',
} as const;
/** Phase reported by `update.progress`. */
export type UpdatePhase = (typeof UpdatePhase)[keyof typeof UpdatePhase];

/** Payload of `WsPushKind.UserRevoked`. */
export interface UserRevokedPush {
  /** Revoked user. */
  userId: string;
  /** Reason. */
  reason: string;
}

/** Payload of `ServerCommandType.Wake`. */
export interface WakeCommand {
  /** MAC of the PC to wake, `AA:BB:CC:DD:EE:FF`. */
  targetMac: string;
}

/** WS frame type (SERVER_API.md §6). */
export const WsFrameType = {
  /** Server → Agent command; must be acked. */
  Command: 'command',
  /** Agent → Server ack of a command. */
  Ack: 'ack',
  /** Agent → Server event; not acked. */
  Event: 'event',
  /** Keepalive request (server every 20 s). */
  Ping: 'ping',
  /** Keepalive reply (within 10 s). */
  Pong: 'pong',
  /** Server → Agent push; not acked. */
  Push: 'push',
} as const;
/** WS frame type (SERVER_API.md §6). */
export type WsFrameType = (typeof WsFrameType)[keyof typeof WsFrameType];

/** Server → Agent pushes (`WsFrameType.Push`, SERVER_API.md §6.3). */
export const WsPushKind = {
  /** Payload `Balance` → IPC `wallet.updated`. */
  WalletUpdated: 'walletUpdated',
  /** Payload `ChatMessage` → IPC `chat.message`. */
  ChatMessage: 'chatMessage',
  /** Payload `Notification` → IPC `notification.push`. */
  Notification: 'notification',
  /** Payload `Order` → IPC `notification.push` + `shop.orderUpdated`. */
  OrderUpdated: 'orderUpdated',
  /** Payload `Booking` → IPC `notification.push`. */
  BookingUpdated: 'bookingUpdated',
  /** Payload `Tournament` → IPC `notification.push`. */
  TournamentUpdated: 'tournamentUpdated',
  /** Payload `Session` → reconcile + IPC `session.updated`. */
  SessionUpdated: 'sessionUpdated',
  /** Payload `PcStatusChangedPush` → seat-map cache. */
  PcStatusChanged: 'pcStatusChanged',
  /** Payload `UserRevokedPush` → IPC `auth.expired{revoked}`, end session. */
  UserRevoked: 'userRevoked',
} as const;
/** Server → Agent pushes (`WsFrameType.Push`, SERVER_API.md §6.3). */
export type WsPushKind = (typeof WsPushKind)[keyof typeof WsPushKind];

/** Semantics of `ProcessAllowlistPolicy.Patterns`. */
export const AllowlistMode = {
  /** Only matching processes may run. */
  Allow: 'allow',
  /** Matching processes are killed. */
  Deny: 'deny',
} as const;
/** Semantics of `ProcessAllowlistPolicy.Patterns`. */
export type AllowlistMode = (typeof AllowlistMode)[keyof typeof AllowlistMode];

/** Anti-cheat policy. */
export interface AntiCheatPolicy {
  /** Subsystems whose drivers/services must be healthy. */
  required: AntiCheatKind[];
  /** Block launches / lock session on violations. */
  blockOnViolation: boolean;
}

/**
 * Explorer / input lockdown. Key combos use the grammar `(Ctrl|Alt|Shift|Win)(\+(Ctrl|Alt|Shift|Win))*\+<Key>` with
 * Win32 virtual-key names without `VK_`.
 */
export interface ExplorerPolicy {
  /** Disable Task Manager. */
  disableTaskManager: boolean;
  /** Disable the Run dialog. */
  disableRun: boolean;
  /** Disable Settings / Control Panel. */
  disableSettings: boolean;
  /** Hide the taskbar. */
  hideTaskbar: boolean;
  /** Block Alt+Tab. */
  disableAltTab: boolean;
  /** Block the Windows key. */
  disableWinKey: boolean;
  /** Additional blocked combos, e.g. `Ctrl+Shift+Esc`. */
  blockedKeyCombos: string[];
}

/** Kiosk UI policy. */
export interface KioskPolicy {
  /** Idle lock timeout. */
  idleTimeoutSec: number;
  /** Interval between ad breaks. */
  adsIntervalSec: number;
  /** Allow the on-screen keyboard. */
  allowVirtualKeyboard: boolean;
}

/** Power policy. */
export interface PowerPolicy {
  /** Shut down after this many idle minutes; `null` = never. */
  idleShutdownMin?: number | null;
  /** Daily shutdown time (local `HH:mm`); `null` = none. */
  scheduledShutdown?: string | null;
}

/** Process allow/deny list; patterns are wildcard image names (`*cheat*`). */
export interface ProcessAllowlistPolicy {
  /** Allow-list or deny-list semantics. */
  mode: AllowlistMode;
  /** Wildcard patterns. */
  patterns: string[];
}

/** Shell replacement for the kiosk user. */
export interface ShellReplacementPolicy {
  /** Replace `explorer.exe`. */
  enabled: boolean;
  /** Path of the shell executable. */
  shellExe: string;
}

/** Update policy (overrides `agent.json → updates`). */
export interface UpdatesPolicy {
  /** Update channel. */
  channel: UpdateChannel;
  /** Apply staged updates automatically when idle. */
  autoInstall: boolean;
}

/** USB device policy. */
export interface UsbPolicy {
  /** Allow USB mass storage. */
  allowStorage: boolean;
  /** Allow USB HID devices. */
  allowHid: boolean;
}

/** DNS-based web filter. */
export interface WebFilterPolicy {
  /** Filter active. */
  enabled: boolean;
  /** Wildcard domains to block. */
  blockedDomains: string[];
  /** Non-empty = allow-list mode. */
  allowedDomains: string[];
  /** Filtering DNS resolvers to enforce. */
  dnsServers: string[];
}

/** Enforced PC policy (IPC_PROTOCOL.md §6.18, ARCHITECTURE.md §12.3). Snapshot persisted to `policies.json`. */
export interface Policy {
  /** Monotonic server-assigned version. */
  version: number;
  /** Last change. */
  updatedAt: string;
  /** Shell replacement. */
  shellReplacement: ShellReplacementPolicy;
  /** Process allow/deny list. */
  processAllowlist: ProcessAllowlistPolicy;
  /** USB policy. */
  usb: UsbPolicy;
  /** Web filter. */
  webFilter: WebFilterPolicy;
  /** Explorer lockdown. */
  explorer: ExplorerPolicy;
  /** Power policy. */
  power: PowerPolicy;
  /** Update policy. */
  updates: UpdatesPolicy;
  /** Anti-cheat policy (wire key `anticheat`). */
  anticheat: AntiCheatPolicy;
  /** Kiosk policy. */
  kiosk: KioskPolicy;
}

/** Response of `policy.reload`. */
export interface PolicyReloadResponse {
  /** Policy now in effect. */
  policy: Policy;
  /** Where it came from. */
  source: PolicySource;
  /** Whether it was (re)applied. */
  applied: boolean;
  /** Top-level sections that changed. */
  changed: string[];
}

// ---- BEGIN MANUAL ----
import type { Notification, ShowAdsArgs } from './events.js';
import type { AntiCheatReport, Game, GameInstallStatus, LaunchRequest, LaunchResult } from './games.js';
import type { PcInfo } from './pc.js';
import type { SessionEndResult, SessionEndedEvent, SessionStartedEvent } from './session.js';
import type { Loyalty, ProfileUpdateRequest, QrLoginStart, UserStats } from './user.js';
import type { Balance, TopupIntent, Transaction } from './wallet.js';
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
function isRecord(value: unknown): value is JsonObject {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** All error codes in declaration order. */
export const ERROR_CODES: readonly ErrorCode[] = Object.values(ErrorCode);

const ERROR_CODE_SET: ReadonlySet<string> = new Set<string>(ERROR_CODES);

/** `true` when `value` is a known {@link ErrorCode}. */
export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && ERROR_CODE_SET.has(value);
}

/** `true` when the same request may succeed if repeated later (`timeout`, `rateLimited`, `serverUnavailable`, `agentOffline`). */
export function isRetryable(code: ErrorCode): boolean {
  return (
    code === ErrorCode.Timeout ||
    code === ErrorCode.RateLimited ||
    code === ErrorCode.ServerUnavailable ||
    code === ErrorCode.AgentOffline
  );
}

/** `true` for codes that mean the caller must (re)authenticate (`unauthorized`, `forbidden`). */
export function isAuthFailure(code: ErrorCode): boolean {
  return code === ErrorCode.Unauthorized || code === ErrorCode.Forbidden;
}

/** HTTP status equivalent of each error code (IPC_PROTOCOL.md §5). */
export const ERROR_CODE_HTTP_STATUS: Readonly<Record<ErrorCode, number>> = {
  unauthorized: 401,
  forbidden: 403,
  notFound: 404,
  validation: 400,
  conflict: 409,
  insufficientFunds: 402,
  sessionNotActive: 409,
  sessionAlreadyActive: 409,
  gameNotInstalled: 409,
  gameLaunchFailed: 500,
  accountPoolExhausted: 409,
  antiCheatBlocked: 403,
  policyDenied: 403,
  agentOffline: 503,
  serverUnavailable: 503,
  timeout: 504,
  rateLimited: 429,
  internal: 500,
  protocolError: 400,
  versionMismatch: 426,
};
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
const IPC_KIND_SET: ReadonlySet<string> = new Set<string>(Object.values(IpcKind));
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** One pipe frame (IPC_PROTOCOL.md §2); `payload` and `error` keys are always present. */
export interface IpcEnvelope<T = JsonObject> {
  /** Protocol major. */
  v: number;
  /** Request id generated by the sender; a response copies it; events use a fresh id. */
  id: string;
  /** Envelope kind. */
  kind: IpcKind;
  /** Message name `<domain>.<action>`. */
  name: string;
  /** Sender wall clock (UTC), informational only. */
  ts: string;
  /** Body or null when the message carries no data. */
  payload: T | null;
  /** Non-null only on a response; when set, `payload` is null. */
  error: IpcError | null;
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Converts a server error to an {@link IpcError}; `traceId` is moved into `details.traceId`. */
export function serverErrorToIpcError(error: ServerError): IpcError {
  return { code: error.code, message: error.message, details: { ...(error.details ?? {}), traceId: error.traceId } };
}

/** Type guard for {@link IpcError}: known `code`, string `message`, `details` null/absent/object. */
export function isIpcError(value: unknown): value is IpcError {
  if (!isRecord(value)) {
    return false;
  }
  const details = value['details'];
  return (
    isErrorCode(value['code']) &&
    typeof value['message'] === 'string' &&
    (details === null || details === undefined || isRecord(details))
  );
}

/** `true` for `<domain>.<action>` where both parts are non-empty ASCII letters (≤ 64 chars). */
export function isValidIpcName(name: string): boolean {
  return name.length <= 64 && /^[A-Za-z]+\.[A-Za-z]+$/.test(name);
}

/** Type guard for {@link IpcEnvelope} (structural rules of IPC_PROTOCOL.md §2; `payload`/`error` may be absent on read). */
export function isIpcEnvelope(value: unknown): value is IpcEnvelope<JsonObject> {
  if (!isRecord(value)) {
    return false;
  }
  const { v, id, kind, name, ts, payload, error } = value;
  if (
    typeof v !== 'number' ||
    !Number.isInteger(v) ||
    typeof id !== 'string' ||
    id.length === 0 ||
    typeof kind !== 'string' ||
    !IPC_KIND_SET.has(kind) ||
    typeof name !== 'string' ||
    !isValidIpcName(name) ||
    typeof ts !== 'string'
  ) {
    return false;
  }
  const payloadOk = payload === null || payload === undefined || isRecord(payload);
  const errorOk = error === null || error === undefined || (kind === IpcKind.Response && isIpcError(error));
  const exclusive = !(error !== null && error !== undefined && isRecord(payload));
  return payloadOk && errorOk && exclusive;
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** All request names in declaration order. */
export const AGENT_COMMANDS: readonly AgentCommand[] = Object.values(AgentCommand);

const AGENT_COMMAND_SET: ReadonlySet<string> = new Set<string>(AGENT_COMMANDS);

/** `true` when `name` is a known Shell → Agent request name. */
export function isAgentCommand(name: string): name is AgentCommand {
  return AGENT_COMMAND_SET.has(name);
}

/** Response name for a request name: identical except `sys.ping` → `sys.pong`. */
export function responseNameFor(requestName: string): string {
  return requestName === IpcNames.Sys.Ping ? IpcNames.Sys.Pong : requestName;
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
const USER_LEVEL_COMMANDS: ReadonlySet<string> = new Set<string>([
  AgentCommand.AuthLogout,
  AgentCommand.SessionGet,
  AgentCommand.SessionStart,
  AgentCommand.SessionTimeLeft,
  AgentCommand.WalletBalance,
  AgentCommand.WalletHistory,
  AgentCommand.WalletTopupIntent,
  AgentCommand.ShopOrderStatus,
  AgentCommand.ShopOrders,
  AgentCommand.ChatHistory,
  AgentCommand.ChatSend,
  AgentCommand.ChatMarkRead,
  AgentCommand.BookingReserve,
  AgentCommand.BookingCancel,
  AgentCommand.TournamentsJoin,
  AgentCommand.ProfileGet,
  AgentCommand.ProfileUpdate,
  AgentCommand.ProfileStats,
  AgentCommand.ProfileAchievements,
  AgentCommand.ProfileLoyalty,
]);

const SESSION_LEVEL_COMMANDS: ReadonlySet<string> = new Set<string>([
  AgentCommand.SessionPause,
  AgentCommand.SessionResume,
  AgentCommand.SessionEnd,
  AgentCommand.SessionExtend,
  AgentCommand.SessionLock,
  AgentCommand.SessionUnlock,
  AgentCommand.GamesLaunch,
  AgentCommand.GamesKill,
  AgentCommand.AppsLaunch,
  AgentCommand.ShopOrder,
]);

/** Authentication level `command` requires. */
export function requiredAuth(command: AgentCommand): IpcAuthLevel {
  if (command === AgentCommand.AuthHello || command === AgentCommand.SysPing) {
    return IpcAuthLevel.None;
  }
  if (USER_LEVEL_COMMANDS.has(command)) {
    return IpcAuthLevel.User;
  }
  if (SESSION_LEVEL_COMMANDS.has(command)) {
    return IpcAuthLevel.Session;
  }
  return IpcAuthLevel.Hello;
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Response of `games.list` (served from `cache\games.json` when offline). */
export interface GamesListResponse extends PagedResult<Game> {
  /** Catalogue version (ETag-like). */
  catalogVersion: string;
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Response of `wallet.history`. */
export type WalletHistoryResponse = PagedResult<Transaction>;
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** `true` when no field of a `settings.set` request is set (request is invalid). */
export function isSettingsSetRequestEmpty(request: SettingsSetRequest): boolean {
  return Object.values(request).every((v) => v === null || v === undefined);
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Top-level policy section key. */
export type PolicySectionKey = Exclude<keyof Policy, 'version' | 'updatedAt'>;

/** Top-level policy keys in wire order; used for `policy.changed.changed`. */
export const POLICY_SECTION_KEYS: readonly PolicySectionKey[] = [
  'shellReplacement',
  'processAllowlist',
  'usb',
  'webFilter',
  'explorer',
  'power',
  'updates',
  'anticheat',
  'kiosk',
];
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Request/response payload pair per IPC request name; `null` = no payload. */
export interface IpcRequestMap {
  [IpcNames.Auth.Hello]: { request: AuthHelloRequest; response: AuthHelloResponse };
  [IpcNames.Auth.Login]: { request: AuthLoginRequest; response: AuthLoginResponse };
  [IpcNames.Auth.Logout]: { request: AuthLogoutRequest | null; response: AuthLogoutResponse };
  [IpcNames.Auth.Status]: { request: null; response: AuthStatusResponse };
  [IpcNames.Auth.QrStart]: { request: null; response: QrLoginStart };
  [IpcNames.Session.Get]: { request: null; response: Session | null };
  [IpcNames.Session.Start]: { request: SessionStartRequest; response: Session };
  [IpcNames.Session.Pause]: { request: SessionPauseRequest | null; response: Session };
  [IpcNames.Session.Resume]: { request: null; response: Session };
  [IpcNames.Session.End]: { request: SessionEndRequest | null; response: SessionEndResult };
  [IpcNames.Session.Extend]: { request: SessionExtendRequest; response: Session };
  [IpcNames.Session.Lock]: { request: SessionLockRequest | null; response: Session };
  [IpcNames.Session.Unlock]: { request: SessionUnlockRequest; response: Session };
  [IpcNames.Session.TimeLeft]: { request: null; response: SessionTimeLeftResponse };
  [IpcNames.Games.List]: { request: GamesListRequest | null; response: GamesListResponse };
  [IpcNames.Games.Get]: { request: GamesGetRequest; response: Game };
  [IpcNames.Games.Launch]: { request: GamesLaunchRequest; response: LaunchResult };
  [IpcNames.Games.Kill]: { request: GamesKillRequest | null; response: GamesKillResponse };
  [IpcNames.Games.Running]: { request: null; response: GamesRunningResponse };
  [IpcNames.Games.InstallStatus]: { request: GamesInstallStatusRequest; response: GameInstallStatus };
  [IpcNames.Apps.List]: { request: null; response: AppsListResponse };
  [IpcNames.Apps.Launch]: { request: AppsLaunchRequest; response: AppsLaunchResponse };
  [IpcNames.Wallet.Balance]: { request: null; response: Balance };
  [IpcNames.Wallet.Tariffs]: { request: WalletTariffsRequest | null; response: WalletTariffsResponse };
  [IpcNames.Wallet.History]: { request: WalletHistoryRequest | null; response: WalletHistoryResponse };
  [IpcNames.Wallet.TopupIntent]: { request: WalletTopupIntentRequest; response: TopupIntent };
  [IpcNames.Shop.Products]: { request: ShopProductsRequest | null; response: ShopProductsResponse };
  [IpcNames.Shop.Order]: { request: ShopOrderRequest; response: Order };
  [IpcNames.Shop.OrderStatus]: { request: ShopOrderStatusRequest; response: Order };
  [IpcNames.Shop.Orders]: { request: ShopOrdersRequest | null; response: ShopOrdersResponse };
  [IpcNames.Chat.History]: { request: ChatHistoryRequest | null; response: ChatHistoryResponse };
  [IpcNames.Chat.Send]: { request: ChatSendRequest; response: ChatMessage };
  [IpcNames.Chat.MarkRead]: { request: ChatMarkReadRequest; response: ChatMarkReadResponse };
  [IpcNames.Booking.Seats]: { request: BookingSeatsRequest; response: BookingSeatsResponse };
  [IpcNames.Booking.Reserve]: { request: BookingReserveRequest; response: Booking };
  [IpcNames.Booking.Cancel]: { request: BookingCancelRequest; response: Booking };
  [IpcNames.Tournaments.List]: { request: TournamentsListRequest | null; response: TournamentsListResponse };
  [IpcNames.Tournaments.Join]: { request: TournamentsJoinRequest; response: Tournament };
  [IpcNames.Tournaments.Leaderboard]: {
    request: TournamentsLeaderboardRequest;
    response: TournamentsLeaderboardResponse;
  };
  [IpcNames.Profile.Get]: { request: null; response: User };
  [IpcNames.Profile.Update]: { request: ProfileUpdateRequest; response: User };
  [IpcNames.Profile.Stats]: { request: null; response: UserStats };
  [IpcNames.Profile.Achievements]: { request: null; response: ProfileAchievementsResponse };
  [IpcNames.Profile.Loyalty]: { request: null; response: Loyalty };
  [IpcNames.Settings.Get]: { request: null; response: ShellSettings };
  [IpcNames.Settings.Set]: { request: SettingsSetRequest; response: ShellSettings };
  [IpcNames.Sys.Ping]: { request: SysPingRequest; response: SysPongResponse };
  [IpcNames.Sys.PcInfo]: { request: null; response: PcInfo };
  [IpcNames.Sys.Hardware]: { request: SysHardwareRequest | null; response: HardwareInfo };
  [IpcNames.Sys.Metrics]: { request: null; response: PcMetrics };
  [IpcNames.Sys.CallAdmin]: { request: SysCallAdminRequest; response: SysCallAdminResponse };
  [IpcNames.Sys.Reboot]: { request: SysPowerRequest | null; response: ScheduledResult };
  [IpcNames.Sys.Shutdown]: { request: SysPowerRequest | null; response: ScheduledResult };
  [IpcNames.Sys.LockScreen]: { request: SysLockScreenRequest | null; response: OkResponse };
  [IpcNames.Sys.SetVolume]: { request: SetVolumeRequest; response: VolumeState };
  [IpcNames.Sys.SetLocale]: { request: SysSetLocaleRequest; response: SysSetLocaleResponse };
  [IpcNames.Sys.UnlockAdmin]: { request: SysUnlockAdminRequest; response: SysUnlockAdminResponse };
  [IpcNames.Sys.LogClientError]: { request: SysLogClientErrorRequest; response: OkResponse };
  [IpcNames.Sys.AckAdminMessage]: { request: SysAckAdminMessageRequest; response: OkResponse };
  [IpcNames.Policy.Get]: { request: null; response: Policy };
  [IpcNames.Policy.Reload]: { request: PolicyReloadRequest | null; response: PolicyReloadResponse };
  [IpcNames.Update.Check]: { request: null; response: UpdateCheckResponse };
  [IpcNames.Update.Apply]: { request: UpdateApplyRequest; response: UpdateApplyResponse };
}

/** Request payload type of an IPC request name. */
export type IpcRequestOf<N extends AgentCommand> = IpcRequestMap[N]['request'];

/** Response payload type of an IPC request name. */
export type IpcResponseOf<N extends AgentCommand> = IpcRequestMap[N]['response'];
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
const SERVER_COMMAND_TYPE_SET: ReadonlySet<string> = new Set<string>(Object.values(ServerCommandType));

/** `true` when `name` is a known server command type. */
export function isServerCommandType(name: unknown): name is ServerCommandType {
  return typeof name === 'string' && SERVER_COMMAND_TYPE_SET.has(name);
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** `true` when a `refreshConfig` command selects no specific cache (refresh everything). */
export function isRefreshConfigAll(command: RefreshConfigCommand | null | undefined): boolean {
  return command == null || !Object.values(command).some((v) => v === true);
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Payload type per server command. */
export interface ServerCommandPayloadMap {
  lock: LockCommand | null;
  unlock: null;
  message: MessageCommand;
  reboot: PowerCommand;
  shutdown: PowerCommand;
  wake: WakeCommand;
  endSession: EndSessionCommand;
  extendSession: ExtendSessionCommand;
  launchGame: LaunchRequest;
  killGame: KillGameCommand;
  setPolicy: Policy;
  reloadPolicy: null;
  screenshot: ScreenshotCommand;
  remoteControlStart: RemoteControlStartCommand;
  remoteControlStop: RemoteControlStopCommand;
  update: UpdateCommand;
  showAds: ShowAdsArgs;
  setVolume: SetVolumeRequest;
  refreshConfig: RefreshConfigCommand | null;
}

/** Ack result type per server command. */
export interface ServerCommandResultMap {
  lock: null;
  unlock: null;
  message: MessageDeliveryResult;
  reboot: ScheduledResult;
  shutdown: ScheduledResult;
  wake: null;
  endSession: SessionResult;
  extendSession: SessionResult;
  launchGame: LaunchResult;
  killGame: GamesKillResponse;
  setPolicy: SetPolicyResult;
  reloadPolicy: ReloadPolicyResult;
  screenshot: ScreenshotResult;
  remoteControlStart: RemoteControlStartResult;
  remoteControlStop: RemoteControlStopResult;
  update: UpdateApplyResponse;
  showAds: null;
  setVolume: VolumeState;
  refreshConfig: RefreshConfigResult;
}

/** Normalized server command as handled by the Agent's command dispatcher. */
export interface ServerCommand<T extends ServerCommandType = ServerCommandType> {
  /** Command id (dedupe key, 24 h). */
  id: string;
  /** Command type. */
  type: T;
  /** Server timestamp. */
  issuedAt: string;
  /** Typed payload or null. */
  payload?: ServerCommandPayloadMap[T] | null;
  /** Admin login or `system`, when known. */
  issuedBy?: string | null;
  /** Earlier pending command this one cancels. */
  supersedes?: string | null;
  /** Discard (ack with `timeout`) after this time. */
  expiresAt?: string | null;
}

/** `true` when the command's `expiresAt` has passed at `now` (ISO string or Date). */
export function isServerCommandExpired(command: Pick<ServerCommand, 'expiresAt'>, now: string | Date): boolean {
  if (command.expiresAt == null) {
    return false;
  }
  const nowMs = typeof now === 'string' ? Date.parse(now) : now.getTime();
  return Date.parse(command.expiresAt) <= nowMs;
}

/** Wire form of a queued command returned by `GET /agents/{pcId}/commands`. */
export interface ServerCommandEnvelope<T extends ServerCommandType = ServerCommandType> {
  /** Command id. */
  id: string;
  /** Server timestamp. */
  ts: string;
  /** Command type. */
  name: T;
  /** Payload or null. */
  payload?: ServerCommandPayloadMap[T] | null;
  /** Admin login, when known. */
  issuedBy?: string | null;
  /** Earlier pending command this one cancels. */
  supersedes?: string | null;
  /** Expiry. */
  expiresAt?: string | null;
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Body of `POST /agents/{pcId}/commands/{commandId}/ack` and payload of a WS `ack` frame. */
export interface CommandAck<TResult = JsonObject> {
  /** Whether the command succeeded. */
  ok: boolean;
  /** Failure, when `ok` is false. */
  error?: IpcError | null;
  /** Typed result or null. */
  result?: TResult | null;
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Payload type per agent event. */
export interface AgentEventPayloadMap {
  sessionStarted: SessionStartedEvent;
  sessionEnded: SessionEndedEvent;
  gameLaunched: GameLaunchedEvent;
  gameExited: GameExitedEvent;
  anticheatViolation: AntiCheatReport;
  hardwareChanged: HardwareChangedEvent;
  offlineQueueFlushed: OfflineQueueFlushedEvent;
}

/** Agent → server event. */
export interface AgentEvent<T extends AgentEventType = AgentEventType> {
  /** Event type (also the WS frame `name`). */
  type: T;
  /** Event time. */
  at: string;
  /** Typed payload. */
  payload?: AgentEventPayloadMap[T] | null;
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
const WS_PUSH_KIND_SET: ReadonlySet<string> = new Set<string>(Object.values(WsPushKind));

/** `true` when `name` is a known push kind. */
export function isWsPushKind(name: unknown): name is WsPushKind {
  return typeof name === 'string' && WS_PUSH_KIND_SET.has(name);
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Payload type per push kind. */
export interface WsPushPayloadMap {
  walletUpdated: Balance;
  chatMessage: ChatMessage;
  notification: Notification;
  orderUpdated: Order;
  bookingUpdated: Booking;
  tournamentUpdated: Tournament;
  sessionUpdated: Session;
  pcStatusChanged: PcStatusChangedPush;
  userRevoked: UserRevokedPush;
}

/** Ack body inside an `ack` frame. */
export interface WsAck<TResult = JsonObject> extends CommandAck<TResult> {
  /** Id of the command being acknowledged. */
  id: string;
}

/** Maximum WS frame size in bytes. */
export const WS_MAX_FRAME_BYTES = 1024 * 1024;

/** WS subprotocol negotiated on connect. */
export const WS_SUBPROTOCOL = 'clubshell.v1';

/** One text frame on `wss://<server>/ws/agent`; `payload` key is always present. */
export interface WsFrame<TPayload = JsonObject> {
  /** Frame type. */
  type: WsFrameType;
  /** Frame id (command id for commands). */
  id: string;
  /** Sender timestamp. */
  ts: string;
  /** `ServerCommandType` / `AgentEventType` / `WsPushKind` wire name; required for command/event/push. */
  name?: string | null;
  /** Body or null. */
  payload: TPayload | null;
  /** Ack body; required for `ack`. */
  ack?: WsAck | null;
  /** Command only: earlier pending command this one cancels. */
  supersedes?: string | null;
  /** Command only: discard after this time. */
  expiresAt?: string | null;
}
// ---- END MANUAL ----
