// <auto-generated> by tools/ContractsGen from ClubShell.Contracts v1.0.0 — edit only inside MANUAL blocks

import type { IpcError, JsonObject, Policy, UpdateComponent, UpdateManifest, UpdatePhase } from './commands.js';
import type { GameState } from './games.js';
import type { ConnectivityState } from './pc.js';
import type { AuthExpiredReason } from './user.js';

/** Media type of an ad item. */
export const AdMediaType = {
  /** Still image. */
  Image: 'image',
  /** Video. */
  Video: 'video',
} as const;
/** Media type of an ad item. */
export type AdMediaType = (typeof AdMediaType)[keyof typeof AdMediaType];

/** One ad in a `ShowAdsArgs` playlist. */
export interface AdItem {
  /** Media URL. */
  url: string;
  /** Media type. */
  type: AdMediaType;
  /** Display duration. */
  durationSec: number;
}

/** Payload of `auth.expired`; the Shell returns to the login screen. */
export interface AuthExpired {
  /** Why the user context was invalidated. */
  reason: AuthExpiredReason;
}

/** Payload of `sys.connectivity` (transitions + every 60 s). */
export interface ConnectivityEvent {
  /** Connectivity. */
  state: ConnectivityState;
  /** When the state was entered. */
  since: string;
  /** Outbox size. */
  queuedEvents: number;
  /** Last heartbeat latency, when online. */
  serverLatencyMs?: number | null;
}

/** Payload of `game.stateChanged`. */
export interface GameStateChanged {
  /** Game. */
  gameId: string;
  /** Game title. */
  title: string;
  /** New state. */
  state: GameState;
  /** Transition time. */
  at: string;
  /** Process id, when known. */
  pid?: number | null;
  /** Exit code (`GameState.Exited`). */
  exitCode?: number | null;
  /** Failure (`GameState.Failed`). */
  error?: IpcError | null;
}

/** Payload of `policy.changed`. */
export interface PolicyChanged {
  /** Policy version. */
  version: number;
  /** Policy timestamp. */
  updatedAt: string;
  /** Top-level sections that changed. */
  changed: string[];
  /** Policy now in effect. */
  policy: Policy;
}

/** Remote-control state (`admin.remoteControl`). */
export const RemoteControlState = {
  /** Remote control started. */
  Started: 'started',
  /** Remote control stopped. */
  Stopped: 'stopped',
} as const;
/** Remote-control state (`admin.remoteControl`). */
export type RemoteControlState = (typeof RemoteControlState)[keyof typeof RemoteControlState];

/** Payload of `admin.remoteControl`. */
export interface RemoteControlEvent {
  /** Started/stopped. */
  state: RemoteControlState;
  /** Transition time. */
  at: string;
  /** Show the on-screen indicator. */
  showIndicator: boolean;
  /** Admin name, when known. */
  adminName?: string | null;
}

/** UI command carried by `shell.command`. */
export const ShellCommandKind = {
  /** Show the lock screen; args `LockCommand`. */
  Lock: 'lock',
  /** Hide the lock screen; no args. */
  Unlock: 'unlock',
  /** Reboot notice (Agent performs the reboot); args `ShellRebootArgs`. */
  Reboot: 'reboot',
  /** Play ads; args `ShowAdsArgs`. */
  ShowAds: 'showAds',
  /** Show a message; args `ShowMessageArgs`. */
  ShowMessage: 'showMessage',
} as const;
/** UI command carried by `shell.command`. */
export type ShellCommandKind = (typeof ShellCommandKind)[keyof typeof ShellCommandKind];

/** Args of `ShellCommandKind.Reboot` (informational; the Agent performs the reboot). */
export interface ShellRebootArgs {
  /** Seconds until reboot. */
  delaySec: number;
  /** Message to display. */
  message?: string | null;
}

/** Args of `ShellCommandKind.ShowAds` and payload of the `showAds` server command. */
export interface ShowAdsArgs {
  /** Playlist. */
  items: AdItem[];
  /** User may skip. */
  skippable: boolean;
}

/** Payload of `update.available`. */
export interface UpdateAvailable {
  /** Newer package. */
  manifest: UpdateManifest;
  /** Installed version of that component. */
  current: string;
}

/** Payload of `update.progress` (≤ 2/s). */
export interface UpdateProgress {
  /** Component. */
  component: UpdateComponent;
  /** Package version. */
  version: string;
  /** Phase. */
  phase: UpdatePhase;
  /** 0–100. */
  percent: number;
  /** Bytes processed. */
  bytesDone: number;
  /** Total bytes. */
  bytesTotal: number;
  /** Failure (`UpdatePhase.Failed`). */
  error?: IpcError | null;
}

/** Payload of `update.ready` (package staged and verified). */
export interface UpdateReady {
  /** Component. */
  component: UpdateComponent;
  /** Package version. */
  version: string;
  /** Whether applying restarts the component. */
  restartRequired: boolean;
  /** Will be applied even during a session. */
  mandatory: boolean;
  /** Scheduled apply time, when known. */
  applyAt?: string | null;
}

/** Optional call-to-action of a `Notification`. */
export interface NotificationAction {
  /** Button label. */
  label: string;
  /** Frontend route (e.g. `/shop`) or an `AgentCommand` IPC name (e.g. `wallet.topupIntent`). */
  command: string;
  /** Arguments for `command`. */
  args?: JsonObject | null;
}

/** Notification severity. */
export const NotificationLevel = {
  /** Informational. */
  Info: 'info',
  /** Warning. */
  Warning: 'warning',
  /** Error. */
  Error: 'error',
  /** Success. */
  Success: 'success',
} as const;
/** Notification severity. */
export type NotificationLevel = (typeof NotificationLevel)[keyof typeof NotificationLevel];

/** Payload of `admin.message`. */
export interface AdminMessage {
  /** Message id (ack via `sys.ackAdminMessage`). */
  id: string;
  /** Sender name. */
  from: string;
  /** Text. */
  text: string;
  /** Severity. */
  level: NotificationLevel;
  /** User must acknowledge (modal). */
  requiresAck: boolean;
  /** Receipt time. */
  at: string;
}

/** Args of `ShellCommandKind.ShowMessage`. */
export interface ShowMessageArgs {
  /** Title. */
  title: string;
  /** Body. */
  body: string;
  /** Severity. */
  level: NotificationLevel;
  /** Auto-dismiss after this many seconds. */
  ttlSec?: number | null;
}

/** Toast/notification (IPC_PROTOCOL.md §6.21). Payload of `notification.push`. */
export interface Notification {
  /** Notification id. */
  id: string;
  /** Title. */
  title: string;
  /** Body text. */
  body: string;
  /** Severity. */
  level: NotificationLevel;
  /** Auto-dismiss after this many seconds; `null` = sticky. */
  ttlSec?: number | null;
  /** Optional call-to-action. */
  action?: NotificationAction | null;
}

// ---- BEGIN MANUAL ----
import { IpcNames, type LockCommand } from './commands.js';
import type { PcMetrics } from './pc.js';
import type { Session, SessionEndedEvent, SessionWarning } from './session.js';
import type { Order } from './shop.js';
import type { ChatMessage } from './user.js';
import type { Balance } from './wallet.js';
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Typed `args` per {@link ShellCommandKind}. */
export interface ShellCommandArgsMap {
  lock: LockCommand | null;
  unlock: null;
  reboot: ShellRebootArgs;
  showAds: ShowAdsArgs;
  showMessage: ShowMessageArgs;
}

/** Payload of `shell.command`; discriminated on `command`, `args` key always present. */
export type ShellCommand = {
  [K in ShellCommandKind]: {
    /** Command kind. */
    command: K;
    /** Typed args or null. */
    args: ShellCommandArgsMap[K];
    /** Originating server command id (or a fresh id for Agent-originated commands). */
    commandId: string;
  };
}[ShellCommandKind];
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Payload type per Agent → Shell event name (IPC_PROTOCOL.md §8). */
export interface AgentEventMap {
  [IpcNames.Events.SessionUpdated]: Session;
  [IpcNames.Events.SessionWarning]: SessionWarning;
  [IpcNames.Events.SessionEnded]: SessionEndedEvent;
  [IpcNames.Events.WalletUpdated]: Balance;
  [IpcNames.Events.ChatMessage]: ChatMessage;
  [IpcNames.Events.NotificationPush]: Notification;
  [IpcNames.Events.AdminMessage]: AdminMessage;
  [IpcNames.Events.AdminRemoteControl]: RemoteControlEvent;
  [IpcNames.Events.GameStateChanged]: GameStateChanged;
  [IpcNames.Events.PolicyChanged]: PolicyChanged;
  [IpcNames.Events.UpdateAvailable]: UpdateAvailable;
  [IpcNames.Events.UpdateProgress]: UpdateProgress;
  [IpcNames.Events.UpdateReady]: UpdateReady;
  [IpcNames.Events.SysMetrics]: PcMetrics;
  [IpcNames.Events.SysConnectivity]: ConnectivityEvent;
  [IpcNames.Events.ShellCommand]: ShellCommand;
  [IpcNames.Events.AuthExpired]: AuthExpired;
  [IpcNames.Events.ShopOrderUpdated]: Order;
}

/** Agent → Shell event name (`'session.updated' | 'session.warning' | ...`). */
export type AgentEventName = keyof AgentEventMap;

/** Discriminated union of every Agent → Shell event: `{ name, payload }`. */
export type ShellEvent = {
  [K in AgentEventName]: {
    /** Event name. */
    name: K;
    /** Typed payload. */
    payload: AgentEventMap[K];
  };
}[AgentEventName];

/** All Agent → Shell event names in declaration order. */
export const AGENT_EVENT_NAMES: readonly AgentEventName[] = Object.values(IpcNames.Events);

const AGENT_EVENT_NAME_SET: ReadonlySet<string> = new Set<string>(AGENT_EVENT_NAMES);

/** `true` when `name` is a known Agent → Shell event name. */
export function isAgentEventName(name: string): name is AgentEventName {
  return AGENT_EVENT_NAME_SET.has(name);
}
// ---- END MANUAL ----
