// <auto-generated> by tools/ContractsGen from ClubShell.Contracts v1.0.0 — edit only inside MANUAL blocks

import type { IpcError, JsonObject } from './commands.js';

/** Why an account-pool lease is released. */
export const AccountLeaseReleaseReason = {
  /** Game exited. */
  Exit: 'exit',
  /** Session ended. */
  SessionEnd: 'sessionEnd',
  /** Launch failed. */
  LaunchFailed: 'launchFailed',
  /** Manual / admin release. */
  Manual: 'manual',
} as const;
/** Why an account-pool lease is released. */
export type AccountLeaseReleaseReason = (typeof AccountLeaseReleaseReason)[keyof typeof AccountLeaseReleaseReason];

/** Action the Agent took in response to an anti-cheat finding. */
export const AntiCheatAction = {
  /** Reported only. */
  None: 'none',
  /** Launch was refused (`antiCheatBlocked`). */
  BlockedLaunch: 'blockedLaunch',
  /** Running game was killed. */
  KilledGame: 'killedGame',
  /** Session was locked pending admin. */
  LockedSession: 'lockedSession',
} as const;
/** Action the Agent took in response to an anti-cheat finding. */
export type AntiCheatAction = (typeof AntiCheatAction)[keyof typeof AntiCheatAction];

/** Well-known values of `AntiCheatReport.Check` (SERVER_API.md §4.14). */
export const AntiCheatChecks = {
  /** Required anti-cheat driver is not installed. */
  DriverMissing: 'driverMissing',
  /** Anti-cheat service is stopped. */
  ServiceStopped: 'serviceStopped',
  /** UEFI Secure Boot is off. */
  SecureBootOff: 'secureBootOff',
  /** TPM is absent or disabled. */
  TpmOff: 'tpmOff',
  /** Hypervisor-enforced code integrity is off. */
  HvciOff: 'hvciOff',
  /** Windows test-signing mode is on. */
  TestSigningOn: 'testSigningOn',
  /** A blocked process was found running. */
  BlockedProcess: 'blockedProcess',
  /** A foreign module was injected into a game process. */
  InjectedModule: 'injectedModule',
  /** Virtual machine detected. */
  VmDetected: 'vmDetected',
  /** Debugger attached to a game process. */
  DebuggerAttached: 'debuggerAttached',
} as const;
/** One of the {@link AntiCheatChecks} values. */
export type AntiCheatCheck = (typeof AntiCheatChecks)[keyof typeof AntiCheatChecks];

/** Anti-cheat subsystem a game depends on. */
export const AntiCheatKind = {
  /** No anti-cheat. */
  None: 'none',
  /** Easy Anti-Cheat. */
  Eac: 'eac',
  /** BattlEye. */
  BattlEye: 'battlEye',
  /** Riot Vanguard (kernel driver, Secure Boot / TPM prerequisites). */
  Vanguard: 'vanguard',
  /** FACEIT client. */
  Faceit: 'faceit',
  /** Activision Ricochet. */
  Ricochet: 'ricochet',
} as const;
/** Anti-cheat subsystem a game depends on. */
export type AntiCheatKind = (typeof AntiCheatKind)[keyof typeof AntiCheatKind];

/** Result of the pre-launch anti-cheat check, embedded in a `LaunchReport`. */
export interface AntiCheatCheckResult {
  /** Subsystem checked. */
  kind: AntiCheatKind;
  /** Whether prerequisites were satisfied. */
  ok: boolean;
  /** Failed check (`AntiCheatChecks`) when `ok` is `false`. */
  reason?: string | null;
}

/** Severity of an anti-cheat finding. */
export const AntiCheatSeverity = {
  /** Informational. */
  Info: 'info',
  /** Soft violation; launch allowed unless policy blocks. */
  Warning: 'warning',
  /** Hard violation. */
  Critical: 'critical',
} as const;
/** Severity of an anti-cheat finding. */
export type AntiCheatSeverity = (typeof AntiCheatSeverity)[keyof typeof AntiCheatSeverity];

/** Body of `POST /anticheat/report` and payload of the `anticheatViolation` agent event (SERVER_API.md §4.14). */
export interface AntiCheatReport {
  /** Reporting PC. */
  pcId: string;
  /** Session during which the finding occurred, when any. */
  sessionId?: string | null;
  /** Logged-in user, when any. */
  userId?: string | null;
  /** Game concerned, when any. */
  gameId?: string | null;
  /** Subsystem. */
  kind: AntiCheatKind;
  /** Check identifier (`AntiCheatChecks`). */
  check: string;
  /** Severity. */
  severity: AntiCheatSeverity;
  /** Structured evidence (process names, module paths, registry values). Never contains credentials. */
  details: JsonObject;
  /** Time of the finding. */
  at: string;
  /** Action the Agent took. */
  actionTaken: AntiCheatAction;
}

/** Non-game application allowed on the kiosk (IPC_PROTOCOL.md §6.10). */
export interface App {
  /** App id. */
  id: string;
  /** Title. */
  title: string;
  /** Executable path (allow-listed by the Agent). */
  exePath: string;
  /** Icon URL. */
  iconUrl: string;
  /** Category (`AppCategories`). */
  category: string;
  /** Allowed after policy evaluation. */
  allowed: boolean;
}

/** Well-known values of `App.Category`. */
export const AppCategories = {
  /** Web browser. */
  Browser: 'browser',
  /** Voice chat client. */
  Voice: 'voice',
  /** Media player. */
  Media: 'media',
  /** Utility. */
  Tool: 'tool',
} as const;
/** One of the {@link AppCategories} values. */
export type AppCategory = (typeof AppCategories)[keyof typeof AppCategories];

/** Pre-signed download of a user's cloud-save bundle. */
export interface CloudSaveDownload {
  /** Pre-signed HTTPS URL. */
  url: string;
  /** Lower-case hex SHA-256 of the bundle. */
  sha256: string;
  /** Bundle size. */
  sizeBytes: number;
}

/** Cloud-save bundle the Agent uploaded before releasing a lease. */
export interface CloudSaveUpload {
  /** Pre-signed URL the bundle was `PUT` to (from `SaveUploadTarget`). */
  uploadUrl?: string | null;
  /** Lower-case hex SHA-256 of the bundle. */
  sha256: string;
  /** Bundle size. */
  sizeBytes: number;
}

/** Body of `POST /games/{id}/accounts/{leaseId}/release`. */
export interface AccountLeaseRelease {
  /** Release reason. */
  reason: AccountLeaseReleaseReason;
  /** Uploaded save bundle, when cloud save is enabled. */
  cloudSave?: CloudSaveUpload | null;
}

/** Response of `games.installStatus`. */
export interface GameInstallStatus {
  /** Game id. */
  gameId: string;
  /** Install present and verified. */
  installed: boolean;
  /** Resolved install directory. */
  installPath?: string | null;
  /** Size on disk in GB. */
  sizeGb: number;
  /** Detected version. */
  version?: string | null;
  /** Last successful verification. */
  verifiedAt?: string | null;
  /** Launcher client present and logged in (where detectable). */
  launcherReady: boolean;
}

/** Minimum hardware specification of a game. */
export interface GameMinSpec {
  /** CPU description. */
  cpu: string;
  /** GPU description. */
  gpu: string;
  /** RAM in MiB. */
  ramMb: number;
}

/** Lifecycle state of a launched game process. */
export const GameState = {
  /** Launcher invoked; waiting for the game window/process. */
  Launching: 'launching',
  /** Game process running. */
  Running: 'running',
  /** Exited normally. */
  Exited: 'exited',
  /** Launch failed. */
  Failed: 'failed',
  /** Killed by the Agent (session end, admin, policy). */
  Killed: 'killed',
} as const;
/** Lifecycle state of a launched game process. */
export type GameState = (typeof GameState)[keyof typeof GameState];

/** Sort order for `games.list`. */
export const GamesSort = {
  /** By server popularity rank, descending. */
  Popularity: 'popularity',
  /** By title, ascending. */
  Title: 'title',
  /** By last played (current user), most recent first. */
  LastPlayed: 'lastPlayed',
} as const;
/** Sort order for `games.list`. */
export type GamesSort = (typeof GamesSort)[keyof typeof GamesSort];

/** Which lifecycle point a `LaunchReport` describes. */
export const LaunchReportPhase = {
  /** Reported right after launch (success or failure). */
  Launch: 'launch',
  /** Reported when the game exits. */
  Exit: 'exit',
} as const;
/** Which lifecycle point a `LaunchReport` describes. */
export type LaunchReportPhase = (typeof LaunchReportPhase)[keyof typeof LaunchReportPhase];

/**
 * Outcome of a launch (IPC_PROTOCOL.md §6.9). Over IPC failures are returned as errors, so `ok` is always `true` there.
 */
export interface LaunchResult {
  /** Success flag. */
  ok: boolean;
  /** Game process id when started. */
  pid?: number | null;
  /** Launch time. */
  startedAt: string;
  /** Account-pool lease used, when any. */
  accountLeaseId?: string | null;
  /** Failure details when `ok` is `false`. */
  error?: IpcError | null;
}

/** Game launcher / store client used to start a game. */
export const LauncherType = {
  /** Steam (`steam://rungameid/<appid>`). */
  Steam: 'steam',
  /** Epic Games Launcher. */
  Epic: 'epic',
  /** Battle.net. */
  BattleNet: 'battleNet',
  /** Riot Client. */
  Riot: 'riot',
  /** EA app. */
  Ea: 'ea',
  /** Ubisoft Connect. */
  Ubisoft: 'ubisoft',
  /** Plain executable, no launcher. */
  Exe: 'exe',
} as const;
/** Game launcher / store client used to start a game. */
export type LauncherType = (typeof LauncherType)[keyof typeof LauncherType];

/**
 * Account-pool lease (`GET /games/{id}/accounts/lease`, SERVER_API.md §4.6). `secret` is AES-256-GCM encrypted with a
 * per-agent key derived from the signing secret (HKDF-SHA256, info `account-pool`), base64 `nonce||ciphertext||tag`.
 * Never logged.
 */
export interface AccountLease {
  /** Lease id. */
  leaseId: string;
  /** Launcher the credentials belong to. */
  launcher: LauncherType;
  /** Account login. */
  username: string;
  /** Encrypted password or token. */
  secret: string;
  /** Launcher-specific extras (`steamGuardSecret`, `authenticatorSeed`, `region`). */
  extra?: JsonObject | null;
  /** Lease TTL. */
  expiresAt: string;
  /** Save bundle to restore before launch, when any. */
  cloudSave?: CloudSaveDownload | null;
}

/**
 * Catalogue game (IPC_PROTOCOL.md §6.8). Local-only fields (`installed`, `installPath`) are filled by the Agent's scan.
 */
export interface Game {
  /** Game id. */
  id: string;
  /** Localized title. */
  title: string;
  /** Launcher used to start it. */
  launcher: LauncherType;
  /** Steam appid, Epic namespace:item, Battle.net code, etc. */
  launcherAppId?: string | null;
  /** Executable; required for `LauncherType.Exe`; may be relative to `installPath`. */
  exePath?: string | null;
  /** Extra command line. */
  args?: string | null;
  /** Resolved local install directory. */
  installPath?: string | null;
  /** Local scan result. */
  installed: boolean;
  /** Categories. */
  category: string[];
  /** Tags. */
  tags: string[];
  /** Cover image (2:3). */
  coverUrl: string;
  /** Wide hero image. */
  heroUrl?: string | null;
  /** Trailer / background video. */
  videoUrl?: string | null;
  /** Localized description; may be empty. */
  description: string;
  /** Minimum age; 0 = none. */
  ageRating: number;
  /** Server rank score. */
  popularity: number;
  /** Last launch by the current user. */
  lastPlayedAt?: string | null;
  /** Needs an account-pool lease. */
  requiresAccount: boolean;
  /** Anti-cheat subsystem. */
  antiCheat: AntiCheatKind;
  /** Minimum spec. */
  minSpec?: GameMinSpec | null;
  /** Install size in GB (1 fraction digit). */
  sizeGb: number;
  /** Installed/catalogue version. */
  version?: string | null;
}

/** Body of `POST /games/{id}/launch-report` (SERVER_API.md §4.6). */
export interface LaunchReport {
  /** Session. */
  sessionId: string;
  /** Player. */
  userId: string;
  /** Launch outcome. */
  result: LaunchResult;
  /** Launch latency in milliseconds. */
  durationMs: number;
  /** Launcher used. */
  launcher: LauncherType;
  /** Pre-launch anti-cheat check. */
  antiCheat: AntiCheatCheckResult;
  /** Lifecycle point. */
  phase: LaunchReportPhase;
  /** Process exit code (`LaunchReportPhase.Exit`). */
  exitCode?: number | null;
  /** Seconds played (`LaunchReportPhase.Exit`). */
  playedSec?: number | null;
}

/** Screen resolution requested for a launch. */
export interface Resolution {
  /** Width in pixels. */
  width: number;
  /** Height in pixels. */
  height: number;
}

/**
 * Full launch request as executed by the Agent (IPC_PROTOCOL.md §6.9); also the payload of the `launchGame` server
 * command.
 */
export interface LaunchRequest {
  /** Game to launch. */
  gameId: string;
  /** Active session. */
  sessionId: string;
  /** Player. */
  userId: string;
  /** Lease a pooled account and inject credentials. */
  useAccountPool: boolean;
  /** Reuse an existing lease. */
  accountLeaseId?: string | null;
  /** Extra command line (policy-sanitized). */
  extraArgs?: string | null;
  /** Requested resolution. */
  resolution?: Resolution | null;
  /** Seconds to wait for the game process/window before failing. */
  launchTimeoutSec: number;
}

/** Game process tracked by the Agent (IPC_PROTOCOL.md §6.9). */
export interface RunningGame {
  /** Game id. */
  gameId: string;
  /** Game title. */
  title: string;
  /** Process id. */
  pid: number;
  /** Launch time. */
  startedAt: string;
  /** Account-pool lease in use, when any. */
  accountLeaseId?: string | null;
  /** Current state. */
  state: GameState;
}

/** Response of `GET /games/{id}/accounts/{leaseId}/save-upload`. */
export interface SaveUploadTarget {
  /** Pre-signed `PUT` URL. */
  uploadUrl: string;
  /** URL expiry. */
  expiresAt: string;
  /** Maximum accepted bundle size. */
  maxBytes: number;
}

// ---- BEGIN MANUAL ----
/** `true` for terminal states (`exited`, `failed`, `killed`). */
export function isGameStateTerminal(state: GameState): boolean {
  return state === GameState.Exited || state === GameState.Failed || state === GameState.Killed;
}
// ---- END MANUAL ----
