// <auto-generated> by tools/ContractsGen from ClubShell.Contracts v1.0.0 — edit only inside MANUAL blocks
//
// Hand-written code (helpers, type guards, typed maps) lives between "BEGIN MANUAL" / "END MANUAL" line comments
// (exact marker text in tools/ContractsGen/Program.cs); ContractsGen carries every such block over, in order, to the
// end of the regenerated file. Everything outside the markers is replaced on regeneration.

export * from './commands.js';
export * from './events.js';
export * from './games.js';
export * from './pc.js';
export * from './session.js';
export * from './shop.js';
export * from './user.js';
export * from './wallet.js';

// ---- BEGIN MANUAL ----
/**
 * `@clubshell/contracts` — TypeScript mirror of `ClubShell.Contracts` (wire format: JSON camelCase, camelCase string
 * enums, UUID strings, ISO-8601 UTC timestamps, `Money = { amount, currency }`, durations in integer seconds).
 */

/** IPC protocol major carried in `IpcEnvelope.v` (IPC_PROTOCOL.md §2). */
export const PROTOCOL_VERSION = 1;

/** Protocol majors accepted by this library, for `versionMismatch` details. */
export const SUPPORTED_PROTOCOL_VERSIONS: readonly number[] = [PROTOCOL_VERSION];

/** Default Agent named pipe (`agent.json → ipc.pipeName` = `clubshell-agent`). */
export const PIPE_NAME = '\\\\.\\pipe\\clubshell-agent';

/** Maximum IPC frame size in bytes (JSON only, excluding the 4-byte length prefix). */
export const MAX_FRAME_BYTES = 4 * 1024 * 1024;
// ---- END MANUAL ----
