// <auto-generated> by tools/ContractsGen from ClubShell.Contracts v1.0.0 — edit only inside MANUAL blocks

import type { Money } from './wallet.js';

/** `data` of `SessionEventType.Charged`. */
export interface SessionChargedData {
  /** Amount charged. */
  amount: Money;
}

/** Body of `POST /sessions` (SERVER_API.md §4.5). Sent with an `Idempotency-Key`. */
export interface SessionCreateRequest {
  /** PC. */
  pcId: string;
  /** Player. */
  userId: string;
  /** Tariff. */
  tariffId: string;
  /** Minutes to buy; required unless the tariff is a package. */
  minutes?: number | null;
  /** Charge now vs open-ended postpaid. */
  prepaid: boolean;
  /** Actual start for offline-created sessions (≤ `maxOfflineMinutes` in the past). */
  startedAt?: string | null;
  /** Agent-generated id used offline; adopted by the server when free. */
  clientSessionId?: string | null;
}

/** Why a session ended. */
export const SessionEndReason = {
  /** User ended it. */
  User: 'user',
  /** Prepaid time ran out. */
  TimeUp: 'timeUp',
  /** Ended by an admin. */
  Admin: 'admin',
  /** Idle timeout. */
  Idle: 'idle',
  /** Agent restarted and could not resume. */
  AgentRestart: 'agentRestart',
  /** Internal error. */
  Error: 'error',
} as const;
/** Why a session ended. */
export type SessionEndReason = (typeof SessionEndReason)[keyof typeof SessionEndReason];

/** Body of `POST /sessions/{id}/end`. */
export interface SessionEndReport {
  /** End reason. */
  reason: SessionEndReason;
  /** Seconds consumed as measured by the Agent. */
  secondsUsed: number;
  /** Actual end time (offline replay). */
  endedAt?: string | null;
}

/** `data` of `SessionEventType.Ended`. */
export interface SessionEndedData {
  /** End reason. */
  reason: SessionEndReason;
}

/** Kind of `SessionEvent`. */
export const SessionEventType = {
  /** Session started. */
  Started: 'started',
  /** Paused. */
  Paused: 'paused',
  /** Resumed. */
  Resumed: 'resumed',
  /** Extended; data = `SessionExtendedData`. */
  Extended: 'extended',
  /** Time warning emitted; data = `SessionWarningData`. */
  Warning: 'warning',
  /** Locked. */
  Locked: 'locked',
  /** Unlocked. */
  Unlocked: 'unlocked',
  /** Ended; data = `SessionEndedData`. */
  Ended: 'ended',
  /** Charged; data = `SessionChargedData`. */
  Charged: 'charged',
} as const;
/** Kind of `SessionEvent`. */
export type SessionEventType = (typeof SessionEventType)[keyof typeof SessionEventType];

/** Body of `POST /sessions/{id}/events` (≤ 100 events; offline replay and lock/unlock/warning audit). */
export interface SessionEventsBatch {
  /** Events in chronological order. */
  events: SessionEvent[];
}
/** Maximum events per batch. */
export const SESSION_EVENTS_MAX = 100;

/** `data` of `SessionEventType.Extended`. */
export interface SessionExtendedData {
  /** Minutes added. */
  minutes: number;
  /** Amount charged for the extension. */
  cost: Money;
}

/** Session state machine (IPC_PROTOCOL.md §6.1, §9.2). */
export const SessionState = {
  /** No session. */
  Idle: 'idle',
  /** Being created on the server / offline store. */
  Starting: 'starting',
  /** Timer running. */
  Active: 'active',
  /** Paused by the user; timer stopped. */
  Paused: 'paused',
  /** Locked (user away / admin); timer keeps running unless the tariff pauses on lock. */
  Locked: 'locked',
  /** Time is up; grace period before forced end. */
  Ending: 'ending',
  /** Finished and settled. */
  Ended: 'ended',
} as const;
/** Session state machine (IPC_PROTOCOL.md §6.1, §9.2). */
export type SessionState = (typeof SessionState)[keyof typeof SessionState];

/** Play session (IPC_PROTOCOL.md §6.4). */
export interface Session {
  /** Session id (client-generated when created offline). */
  id: string;
  /** Player. */
  userId: string;
  /** PC. */
  pcId: string;
  /** State. */
  state: SessionState;
  /** Start time. */
  startedAt: string;
  /** Scheduled end; `null` while `SessionState.Idle`/`SessionState.Starting` or for open-ended postpaid. */
  endsAt?: string | null;
  /** Set while paused/locked. */
  pausedAt?: string | null;
  /** Tariff in effect. */
  tariffId: string;
  /** Remaining seconds; −1 for open-ended postpaid. */
  secondsLeft: number;
  /** Consumed seconds. */
  secondsUsed: number;
  /** Cost accrued so far. */
  cost: Money;
  /** Prepaid (charged up front) vs postpaid. */
  isPrepaid: boolean;
  /** Minute marks already emitted as `session.warning`, e.g. `[10, 5]`. */
  warningsSent: number[];
}
/** Value of `Session.SecondsLeft` for open-ended postpaid sessions. */
export const SESSION_OPEN_ENDED = -1;

/** Settlement returned by `session.end` and `POST /sessions/{id}/end`. */
export interface SessionEndResult {
  /** Final session (state `SessionState.Ended`). */
  session: Session;
  /** Amount charged at settlement (postpaid). */
  charged: Money;
  /** Amount refunded for unused prepaid time. */
  refunded: Money;
}

/** Payload of the `session.ended` IPC event and the `sessionEnded` agent event. */
export interface SessionEndedEvent {
  /** Final session. */
  session: Session;
  /** End reason. */
  reason: SessionEndReason;
  /** Amount charged at settlement. */
  charged: Money;
}

/** Payload of the `sessionStarted` agent event. */
export interface SessionStartedEvent {
  /** New session. */
  session: Session;
}

/** Payload of the `session.warning` event, emitted at each configured minute mark and once at 0. */
export interface SessionWarning {
  /** Session. */
  sessionId: string;
  /** Whole minutes remaining (0 at expiry). */
  minutesLeft: number;
  /** Seconds remaining. */
  secondsLeft: number;
  /** Scheduled end. */
  endsAt: string;
}

/** `data` of `SessionEventType.Warning`. */
export interface SessionWarningData {
  /** Minutes remaining at the time of the warning. */
  minutesLeft: number;
}

// ---- BEGIN MANUAL ----
/** `true` for states in which a session exists and is not finished (`starting` .. `ending`). */
export function isSessionOpen(state: SessionState): boolean {
  return state !== SessionState.Idle && state !== SessionState.Ended;
}

/** `true` when session-scoped IPC requests are allowed (`active` or `paused`). */
export function sessionAllowsRequests(state: SessionState): boolean {
  return state === SessionState.Active || state === SessionState.Paused;
}

/** `true` when the timer is counting down (`active`, `locked`, `ending`). */
export function isSessionTimerRunning(state: SessionState): boolean {
  return state === SessionState.Active || state === SessionState.Locked || state === SessionState.Ending;
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** `true` when the session has no fixed end (`secondsLeft === SESSION_OPEN_ENDED`). */
export function isSessionOpenEnded(session: Session): boolean {
  return session.secondsLeft === SESSION_OPEN_ENDED;
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** Typed `data` per {@link SessionEventType}; `null` for types without data. */
export interface SessionEventDataMap {
  started: null;
  paused: null;
  resumed: null;
  extended: SessionExtendedData;
  warning: SessionWarningData;
  locked: null;
  unlocked: null;
  ended: SessionEndedData;
  charged: SessionChargedData;
}

/** Audit/replay event of a session (IPC_PROTOCOL.md §6.21); `data` shape depends on `type`. */
export interface SessionEvent<T extends SessionEventType = SessionEventType> {
  /** Session. */
  sessionId: string;
  /** Kind. */
  type: T;
  /** Event time. */
  at: string;
  /** Typed extra data or null. */
  data?: SessionEventDataMap[T] | null;
}
// ---- END MANUAL ----
