// <auto-generated> by tools/ContractsGen from ClubShell.Contracts v1.0.0 — edit only inside MANUAL blocks

import type { Money } from './wallet.js';

/** Line of a placed order; `price` is the unit price at order time. */
export interface OrderItem {
  /** Product id. */
  productId: string;
  /** Product title at order time. */
  title: string;
  /** Quantity (1–99). */
  qty: number;
  /** Unit price at order time. */
  price: Money;
}

/** Line of an order being placed (`shop.order` / `POST /shop/orders`). */
export interface OrderLineRequest {
  /** Product id. */
  productId: string;
  /** Quantity (1–99). */
  qty: number;
}
/** Maximum quantity per line. */
export const ORDER_MAX_QTY = 99;
/** Maximum lines per order. */
export const ORDER_MAX_LINES = 20;

/** Body of `POST /shop/orders` (SERVER_API.md §4.9). Sent with an `Idempotency-Key`. */
export interface OrderCreateRequest {
  /** Buyer. */
  userId: string;
  /** Seat to deliver to. */
  pcId: string;
  /** Current session, when any. */
  sessionId?: string | null;
  /** Lines (1–20). */
  items: OrderLineRequest[];
  /** Free-text note for staff. */
  note?: string | null;
}

/** Order lifecycle. */
export const OrderStatus = {
  /** Placed, awaiting staff acceptance; cancellable. */
  Pending: 'pending',
  /** Accepted by staff. */
  Accepted: 'accepted',
  /** Being prepared. */
  Preparing: 'preparing',
  /** On the way to the seat. */
  Delivering: 'delivering',
  /** Delivered. */
  Done: 'done',
  /** Cancelled by the user or staff; charged amount refunded. */
  Cancelled: 'cancelled',
} as const;
/** Order lifecycle. */
export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

/** Shop order (IPC_PROTOCOL.md §6.13). */
export interface Order {
  /** Order id. */
  id: string;
  /** Buyer. */
  userId: string;
  /** Seat to deliver to. */
  pcId: string;
  /** Lines. */
  items: OrderItem[];
  /** Total charged. */
  total: Money;
  /** Current status. */
  status: OrderStatus;
  /** Creation time. */
  createdAt: string;
  /** Last status change. */
  updatedAt: string;
  /** Free-text note for staff. */
  note?: string | null;
}

/** Shop product category. */
export const ProductCategory = {
  /** Hot food. */
  Food: 'food',
  /** Drinks. */
  Drink: 'drink',
  /** Snacks. */
  Snack: 'snack',
  /** Services (e.g. headset rental). */
  Service: 'service',
  /** Merchandise. */
  Merch: 'merch',
  /** Time packages sold through the shop. */
  Time: 'time',
} as const;
/** Shop product category. */
export type ProductCategory = (typeof ProductCategory)[keyof typeof ProductCategory];

/** Shop product (IPC_PROTOCOL.md §6.13). */
export interface Product {
  /** Product id. */
  id: string;
  /** Localized title. */
  title: string;
  /** Category. */
  category: ProductCategory;
  /** Unit price. */
  price: Money;
  /** Image URL. */
  imageUrl: string;
  /** Availability; when served from cache offline this is unknown and shown as available. */
  inStock: boolean;
  /** Remaining quantity, when tracked. */
  stockQty?: number | null;
  /** Free-form tags. */
  tags: string[];
}

// ---- BEGIN MANUAL ----
import { multiplyMoney } from './wallet.js';
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** `true` while the order is still in progress (not `done` / `cancelled`). */
export function isOrderActive(status: OrderStatus): boolean {
  return status !== OrderStatus.Done && status !== OrderStatus.Cancelled;
}
// ---- END MANUAL ----

// ---- BEGIN MANUAL ----
/** `price × qty` of an order line. */
export function orderLineTotal(item: OrderItem): Money {
  return multiplyMoney(item.price, item.qty);
}
// ---- END MANUAL ----
