//! `shop_*` commands (`TAURI_COMMANDS.md` §2.6) → `shop.*` IPC messages. `idempotencyKey` is
//! generated by the frontend once per cart submission and reused on retry.

use clubshell_protocol::commands::{
    names, ShopOrderRequest, ShopOrderStatusRequest, ShopOrdersRequest, ShopOrdersResponse,
    ShopProductsRequest, ShopProductsResponse,
};
use clubshell_protocol::shop::{Order, OrderLineRequest, Product};
use tauri::State;
use uuid::Uuid;

use super::validate;
use crate::state::{AppState, CmdResult, ShellError};

const SEARCH_MAX: usize = 200;
const NOTE_MAX: usize = 200;
const ORDERS_PAGE_MAX: i32 = 200;

/// `shop_products` → `shop.products` (unwrapped `items`).
#[tauri::command]
pub async fn shop_products(
    state: State<'_, AppState>,
    q: Option<ShopProductsRequest>,
) -> CmdResult<Vec<Product>> {
    let mut q = q.unwrap_or_default();
    q.search = validate::optional_text("search", q.search, SEARCH_MAX)?;
    let resp: ShopProductsResponse = state.agent.request(names::shop::PRODUCTS, &q).await?;
    Ok(resp.items)
}

/// `shop_order` → `shop.order`; 1–20 lines, `qty` 1–99.
#[tauri::command]
pub async fn shop_order(state: State<'_, AppState>, req: ShopOrderRequest) -> CmdResult<Order> {
    let req = validate_order(req)?;
    let order: Order = state.agent.request(names::shop::ORDER, &req).await?;
    tracing::info!(order_id = %order.id, lines = order.items.len(), total = %order.total, "order placed");
    Ok(order)
}

/// `shop_order_status` → `shop.orderStatus`.
#[tauri::command]
pub async fn shop_order_status(state: State<'_, AppState>, order_id: Uuid) -> CmdResult<Order> {
    state
        .agent
        .request(
            names::shop::ORDER_STATUS,
            &ShopOrderStatusRequest { order_id },
        )
        .await
}

/// `shop_orders` → `shop.orders`.
#[tauri::command]
pub async fn shop_orders(
    state: State<'_, AppState>,
    q: Option<ShopOrdersRequest>,
) -> CmdResult<ShopOrdersResponse> {
    let q = q.unwrap_or_default();
    validate::paging(q.page, q.page_size, ORDERS_PAGE_MAX)?;
    state.agent.request(names::shop::ORDERS, &q).await
}

fn validate_order(mut req: ShopOrderRequest) -> CmdResult<ShopOrderRequest> {
    if req.items.is_empty() || req.items.len() > OrderLineRequest::MAX_LINES {
        return Err(ShellError::validation(
            "items",
            &format!("must have 1 to {} lines", OrderLineRequest::MAX_LINES),
        ));
    }
    for (i, line) in req.items.iter().enumerate() {
        if line.product_id.is_nil() {
            return Err(ShellError::validation(
                &format!("items[{i}].productId"),
                "required",
            ));
        }
        validate::range(
            &format!("items[{i}].qty"),
            line.qty,
            1,
            OrderLineRequest::MAX_QTY,
        )?;
    }
    if req.idempotency_key.is_nil() {
        return Err(ShellError::validation("idempotencyKey", "required"));
    }
    req.note = validate::optional_text("note", req.note, NOTE_MAX)?;
    Ok(req)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn order(items: Vec<OrderLineRequest>) -> ShopOrderRequest {
        ShopOrderRequest {
            items,
            idempotency_key: Uuid::from_u128(7),
            note: Some("  ".into()),
        }
    }

    #[test]
    fn order_lines_are_checked() {
        let line = |qty| OrderLineRequest {
            product_id: Uuid::from_u128(1),
            qty,
        };
        assert!(validate_order(order(vec![])).is_err());
        assert!(validate_order(order(vec![line(0)])).is_err());
        assert!(validate_order(order(vec![line(100)])).is_err());
        assert!(validate_order(order(vec![line(1); 21])).is_err());
        assert!(validate_order(ShopOrderRequest {
            idempotency_key: Uuid::nil(),
            ..order(vec![line(1)])
        })
        .is_err());
        let ok = validate_order(order(vec![line(2); 20])).unwrap();
        assert_eq!(ok.note, None);
    }
}
